apps/main/src/components/PageRouterSwap/index.tsx
=> fix: router swap wrong token symbol on not enough balance message.

apps/main/src/components/PageCreatePool/SelectTokenModal/ComboBoxTokenPicker.tsx, apps/main/src/networks.ts
Changes:
- Enabled stableswap-ng, twocoin crypto, tricrypto pool creation on Fractal network
- Increased accuracy of token filtering for user added tokens in fuse.js search for pool creation
=> Task enable pool creation on fractal

apps/main/src/components/PagePool/PoolDetails/PoolParameters/index.tsx
Changes:
- Fixed comparison of initial and future A values in pool/advanced tab to determine "up or "down"
=> Fix: Initial and Future A value string check

apps/loan/src/components/PoolInfoData/index.tsx, apps/loan/src/store/createOhlcChartSlice.ts, packages/ui/src/Chart/CandleChart.tsx, packages/ui/src/Chart/ChartWrapper.tsx
Changes:
- Use app state for oracle price to ensure the last data point is accurate in case there hasn't been recent events
- Fixed deleverage liquidation range in chart
- Added refresh button to chart error message
=> Task: update latest oracle price value in chart on store state updates

apps/main/src/networks.ts
Changes:
- Enabled tricypto pool creation on: optimism, gnosis, kava, fantom, avalanche, celo, bsc
=> task: enabled tricrypto pool creation on additional networks

apps/main/package.json, yarn.lock
Changes:
- Update curve-js to 2.56.11
=> chore: update curvejs to 2.56.11

apps/main/src/store/createGasSlice.ts
Changes:
- Enforced number type and limited maxFeePerGas to two decimals on arbitrum
=> fix: update maxFeePerGas decimal limit on arbitrum

apps/lend/package.json, yarn.lock
Changes:
- Updated curve-lending-js to 1.6.9 on Curve Lend
=> chore: update curve-lending-js to 1.6.9

apps/lend/src/components/DetailInfoRate.tsx, apps/lend/src/components/DetailsMarket/components/DetailsLoan.tsx, apps/lend/src/components/DetailsMarket/components/DetailsSupply.tsx, apps/lend/src/components/DetailsMarket/components/DetailsSupplyRewards.tsx, apps/lend/src/components/DetailsMarket/components/MarketParameters.tsx, apps/lend/src/components/DetailsUser/components/DetailsUserSupply.tsx, apps/lend/src/components/PageMarketList/Page.tsx, apps/lend/src/components/PageMarketList/components/MarketListItemContentBody.tsx, apps/lend/src/components/PageMarketList/components/MarketListNoResult.tsx, apps/lend/src/components/PageMarketList/components/TableRowViewContentTable/TableRow.tsx, apps/lend/src/components/PageMarketList/components/TableRowViewContentTable/TableRowMobile.tsx, apps/lend/src/components/PageMarketList/components/TableRowViewContentTable/index.tsx, apps/lend/src/components/PageMarketList/index.tsx, apps/lend/src/components/PageMarketList/types.ts, apps/lend/src/components/SharedCellData/CellRate.tsx, apps/lend/src/components/SharedCellData/CellRewards.tsx, apps/lend/src/components/SharedCellData/CellRewardsTooltip.tsx, apps/lend/src/hooks/useSupplyTotalApr.ts, apps/lend/src/layout/Header.tsx, apps/lend/src/lib/apiLending.ts, apps/lend/src/store/createMarketListSlice.ts, apps/lend/src/store/createUserSlice.ts
- Remove Lend APY and Rewards APR column. Combine them into Total APR column, add Tooltip to show breakdown.
- Reduce Supply market list size.
- Update Rewards tAPR section to Total APR
- Update text Fee to AMM swap fee
-Update mobile view with Total APR
- Update Lend APY to Lend APR
--- 
- Fixed User supply list filter not showing properly.
- Add search params routes for market list when navigating between networks.
=> task: combine APR into one item

apps/lend/src/components/DetailsMarket/components/MarketParameters.tsx
- Add Max TVL only in Advance mode
=> task: show MAX LTV

apps/lend/src/components/AlertFormError.tsx, apps/lend/src/components/AlertFormWarning.tsx, apps/lend/src/components/AlertLoanSummary/components/SummaryFull.tsx, apps/lend/src/components/AlertLoanSummary/components/SummaryPartial.tsx, apps/lend/src/components/AlertLoanSummary/components/SummarySelfLiquidate.tsx, apps/lend/src/components/PageLoanCreate/LoanFormCreate/index.tsx, apps/lend/src/components/PageLoanManage/LoanBorrowMore/index.tsx, apps/lend/src/components/PageLoanManage/LoanBorrowMore/utils.ts, apps/lend/src/components/PageLoanManage/LoanCollateralAdd/index.tsx, apps/lend/src/components/PageLoanManage/LoanCollateralRemove/index.tsx, apps/lend/src/components/PageLoanManage/LoanRepay/index.tsx, apps/lend/src/components/PageLoanManage/LoanSelfLiquidation/index.tsx, apps/lend/src/components/PageLoanManage/LoanSelfLiquidation/types.ts, apps/lend/src/components/PageLoanManage/Page.tsx, apps/lend/src/components/PageMarketList/index.tsx, apps/lend/src/lib/apiLending.ts, apps/lend/src/store/createLoanBorrowMoreSlice.ts, apps/lend/src/store/createLoanRepaySlice.ts, apps/lend/src/store/createLoanSelfLiquidationSlice.ts, packages/tsconfig/nextjs.json, packages/tsconfig/ui.json, packages/ui/package.json, packages/ui/src/utils/utilsWeb3.ts, yarn.lock
| Borrow more | Repay | Self Liquidate |
| --- | --- | --- |
|Borrow more SL error <img width="1251" alt="borrow_more_SL_wallet_collateral" src="https://github.com/curvefi/curve-frontend/assets/6961602/e78eace0-39aa-4072-acf6-f8654c4b4680">|Repay SL in full with Collateral's crvUSD <img width="1252" alt="repay_SL_collateral_collateral_full" src="https://github.com/curvefi/curve-frontend/assets/6961602/316b08e3-4073-4c79-8ac2-16d7384539dd">|Self-liquidate from collateral crvUSD <img width="1278" alt="self_liq_SL_collateral_borrowed" src="https://github.com/curvefi/curve-frontend/assets/6961602/2d7f820b-19a6-47f4-be15-f74dad04cc72"> |
||Repay SL partial error <img width="1252" alt="repay_SL_collateral_collateral_partial" src="https://github.com/curvefi/curve-frontend/assets/6961602/e900ac5e- …
=> fix: soft liquidation repay, borrow more, self-liquidate mode

packages/onboard-helpers/src/index.ts
It was impossible to disable the wallet when using Web3-Onboard 
[a disconnect error by default value or other reason can not set local storage #2227
](https://github.com/blocknative/web3-onboard/issues/2227)
=> fix: onboard disconnect bug

apps/lend/src/components/ChartOhlcWrapper/index.tsx, apps/lend/src/store/createOhlcChartSlice.ts, packages/ui/src/Chart/DialogSelectChart.tsx
Changes:
- Added check to hide oracle pool ohlc data option if the api has no access to oracle pool data for the lending market
=> task: hide oracle pool ohlc data option if api has no oracle pools for market in Lend

apps/lend/src/components/PageLoanCreate/LoanFormCreate/index.tsx
FIxed leverage number to match market list number.
=> fix: replace hardcoded max leverage value with market's max leverage value

packages/ui/src/utils/utilsNetworks.ts
Changes:
- Changed scanTxPath to .io from .com for etherscan links on mainnet
=> task: updated etherscan url link

apps/lend/src/abis/totalSupply.json, apps/lend/src/components/DetailInfoCrvIncentives.tsx, apps/lend/src/components/PageVault/VaultStake/index.tsx, apps/lend/src/hooks/useAbiTotalSupply.tsx, apps/lend/src/hooks/useContract.ts, apps/lend/src/hooks/useSupplyTotalApr.ts, packages/ui/src/Tooltip/TooltipButton.tsx, packages/ui/src/Tooltip/TooltipIcon.tsx
=> task: add CRV and Incentives APR to Stake form

apps/lend/src/components/CampaignRewardsBanner.tsx, apps/lend/src/components/PageLoanCreate/index.tsx, apps/lend/src/components/PageLoanManage/index.tsx, apps/lend/src/components/PageVault/index.tsx
Changes
- Init campaign rewards data from all lend pages
- Fix array spread bug in lend campaign rewards banner component
=> fix: init campaign rewards from all lend pages

apps/lend/src/components/ChartOhlcWrapper/index.tsx, apps/lend/src/store/createOhlcChartSlice.ts, apps/main/src/components/PagePool/PoolDetails/ChartOhlcWrapper/index.tsx, apps/main/src/store/createPoolsSlice.ts
Changes:
- Add oracle price data fallback from "oracle" api data when "llamma" api data is unavailable to display oracle price line in lend ohlc chart
=> Task lend ohlc chart fallback oracle price line

apps/loan/src/components/PageMarketList/components/TableCellTotalCollateral.tsx
- Add $ symbol in Collateral Value's collateral number
=> fix: add $ symbol for total collateral value breakdowns

apps/lend/src/components/DetailsMarket/components/DetailsContracts.tsx
the fe was displaying twice the address of the borrowed token (crvusd) instead of the address of the collateral token
=> fix collateral token address

packages/curve-lib/src/shared/big-decimal/BigDecimal.d.ts, packages/curve-lib/src/shared/big-decimal/BigDecimal.ts
- You can now use the `.fractional` format to create a `BigDecimal` object 
#346
=> `BigDecimal` regex fix

apps/lend/src/hooks/useTitleMapper.tsx, apps/loan/src/components/DetailInfoHealth.tsx, apps/loan/src/components/LoanInfoUser/components/AlertSoftLiquidation.tsx, apps/loan/src/hooks/useTitleMapper.tsx
Updated resources links as the loan details page changed to a loan concepts page.
Currently the links still work because I have a redirect on the resources website, but I will depreciate this after this is merged.
This fixes #369
=> loan details paged changed to loan concepts

apps/main/src/components/PageCreatePool/constants.ts
Changes:
- Updated stableswap 'Fiat Redeemable Stablecoins' preset in pool creation:
- Changed default fee to 0.01% (was 0.04%)
- Changed default A to 1000 (was 200)
=> task: updated stableswap default fee for fiat redeemable stableswap preset

apps/main/src/components/PageCreatePool/constants.ts
Changes:
- Increased offpeg fee multiplier to 5x (was 2x) in 'Fiat Redeemable Stablecoins' stableswap preset
=> task: increase offpeg fee multiplier to 5x in fiat redeemable stableswap preset

apps/loan/package.json, yarn.lock
Changes:
- Upgraded curve-stablecoin-js (@curvefi/stablecoin-api) to 1.5.7 in loan dapp
=> chore: upgrade curve-stablecoin-js to 1.5.7

packages/ui/src/styles/layout.css
-fix Wallet connect mobile view `view all` button
=> fix: wcm z-index override

apps/loan/src/components/PageCrvUsdStaking/StatsBanner/index.tsx, apps/loan/src/components/PageCrvUsdStaking/index.tsx, apps/loan/src/store/createScrvUsdSlice.ts
- Fetch the savings yield data from the Curve API. If a provider is provided, the data is fetched from the vault contract directly.
- That provides more accurate data and works even if our servers are down.
=> feat: retrieve vault data from contract when connected

apps/main/src/components/PoolLabel.tsx
=> fix: always bold pool name

apps/main/src/components/PagePoolList/components/TableHead.tsx
1. Reduce width for TVL when not on Lite network
=> fix: pool list non-lite TVL column width

apps/main/src/components/PageDeployGauge/components/DeployGaugeButton.tsx, apps/main/src/components/PageDeployGauge/index.tsx
Changes:
- Assume false for curve-lite checks in gauge deployment module
- Assumes false if networks store is not initialised
=> fix: bolster curve-lite checks in gauge deployments

apps/loan/src/layout/Header.tsx, apps/main/src/layout/default/index.tsx
Moves "staking" option to the "crvUSD" header
Before:
After:
=> fix: collapse crvUSD menu items

packages/curve-common/src/widgets/Header/AppButtonLinks.tsx
Users find it confusing to require to choose the sub-menu. Therefore we will return to the old behavior, for now.
=> chore: redirect on app button click

apps/main/package.json, yarn.lock
- Update CurveJS to [v2.65.16](https://github.com/curvefi/curve-js/releases/tag/v2.65.16) ([Changes](https://github.com/curvefi/curve-js/compare/v2.65.13...v2.65.16))
=> chore: update curve-js

apps/main/package.json, yarn.lock
Changes:
- Upgrade curvefi/api to 2.65.17 on /main
=> chore: upgrade curvefi/api to 2.65.17 on /main

packages/curve-ui-kit/src/shared/routes.ts
The getAppRoot method gets called with every separate app, so the application host will not always match the window host. Currently, we are incorrectly logging a warning.
=> fix: unnecessary console warning

apps/loan/src/components/TokenLabel.tsx, packages/ui/src/Tooltip/TooltipAlert.tsx, packages/ui/src/Tooltip/TooltipButton.tsx
@0xtutti I've been struggling with making it visible with the yellow primary color, so I've settled with the red from error. This way it's way more in all themes compared to the warning's yellow. I've tried to find a different icon or add a black outline/stroke but wasn't able to find one that looks good.
@DanielSchiavini I've added a hardcoded gap of 0.125 to make it look nicer; I can't be arsed making it responsive with the mui theme given that this will prob get redesigned in the future anyway. In fact, the whole TooltipAlert probably gets replaced some time in the future. Consider this PR a quick fix until we get there.
https://mui.com/material-ui/material-icons/?query=warning
=> fix: warning icon visibility

apps/loan/src/components/TokenLabel.tsx, packages/ui/src/Tooltip/TooltipButton.tsx
Reverts a previous `display: flex` in `TooltipButton.tsx` which was required to vertically align the icon in crvUSD table rows. However, this broke the tooltip rendering elsewhere in the app. Contains an additional commit that only applies `display: flex` to the icon in the specific crvUSD component for which this fix was intentionally for. Maybe not the cleanest solution but I suspect the code will be rewritten using Mui in the future anyway.
=> fix: misplaced tooltip icons

packages/curve-ui-kit/src/widgets/Footer/Sections.tsx
Updated footer links for improved accuracy. I hope it’s fine to update the links only in [packages/curve-ui-kit/src/widgets/Footer/Sections.tsx](https://github.com/curvefi/curve-frontend/blob/2ddb290f87cea7f22fada6c63870dedc39ddbbd3/packages/curve-ui-kit/src/widgets/Footer/Sections.tsx#L84) and not in all apps.
=> update footer links

apps/lend/src/hooks/useVaultShares.ts, packages/ui/src/utils/utilsFormat.ts
Some other examples:
```
formatNumberWithPrecision(123456789123456780, 6) == 123,456,789,123,456,780
formatNumberWithPrecision(12345678912345678, 6) == 12,345,678,912,345,678
formatNumberWithPrecision(1234567891234567.8, 6) == 1,234,567,891,234,568
formatNumberWithPrecision(123456789123456.78, 6) == 123,456,789,123,457
formatNumberWithPrecision(12345678912345.678, 6) == 12,345,678,912,346
formatNumberWithPrecision(1234567891234.5679, 6) == 1,234,567,891,235
formatNumberWithPrecision(123456789123.45679, 6) == 123,456,789,123
formatNumberWithPrecision(12345678912.345678, 6) == 12,345,678,912
formatNumberWithPrecision(1234567891.2345679, 6) == 1,234,567,891
formatNumberWithPrecision(123456789.12345679, 6) == 123,456,789
formatNumberWithPrecision(12345678.91234568, 6) == 12,345,679 …
```
=> feat: new function that considers number precision

packages/curve-ui-kit/src/shared/ui/Metric.tsx, packages/curve-ui-kit/src/shared/ui/stories/Metric.stories.ts, packages/curve-ui-kit/src/utils/index.ts, packages/curve-ui-kit/src/utils/number.ts
* New Metric widget as per Figma, to be used in for example the user profile. Started working on this as part of that feature, but spinned off into a new PR for earlier discussion & merging.
* I've decided not to implement the progress bar and icon yet as there's no need for them yet. I'd rather implement them when a specific use case arises.
* The `abbr` and `suffix` functions are number helper functions I've decided to use instead of `formatNumber`, because of the way we make them stand out in the UI with slightly different styling. I'd rather not dwell too much on the specifics; decimal number harmonization can become a tedious discussion.
* I couldn't decide between one prop for object vs multiple properties, like one `notionalConfig` prop vs multiple like `notionalAbbreviate` and …
=> feat: add new metric widget

packages/ui/src/styles/theme-chad.css
background color for hover state for chad chips was missing, this PR adds them back:
=> styling: fix missing bgcolor for chad chips on hover

packages/ui/src/QueryProvider/index.tsx
I think we can enable TanStack Devtools again; not sure why it was disabled in the first place in fd3f719333b6d405defefaccbe6b0bf3852eb01e as I find it very helpful, and in production builds it gets completely excluded by default (it only gets included if `process.env.NODE_ENV === 'development'`)
Because Cypress tests run with development mode enabled, I've added an extra check to not use the devtools in case Cypress is running. This is because the devtool button's positioning may break some tests. It's not really a big deal as in production the devtools get omitted anyway.
=> chore: enable tanstack devtools when running locally

apps/loan/src/pages/index.tsx
- PAGE_MARKETS starts with a slash, so https://crvusd.curve.fi/#/ethereum/markets/eth/create was giving  404 but https://crvusd.curve.fi/#/ethereum//markets/eth/create currently works :sob:
=> fix: crvUSD market links

apps/lend/src/entities/chain/chain-hooks.ts
a mismatch between the UI chain and the one in the lending lib caused the library to crash
=> fix: crash in lend when switching networks

packages/external-rewards/src/campaigns/Corn.json
update multipliers on corn campaign (from 3x to 6x) to match up multipliers with their dashboard.
=> External rewards: update corn multipliers

packages/curve-ui-kit/src/themes/typography/override-typography.d.ts
I've managed to fix the typing for typography variants. However, I've not been able to fix the typing for typography colors, I think it needs a different approach given that the colors can be used for much more than just colors.
=> fix: broken typography variant typing

apps/loan/src/store/createScrvUsdSlice.ts
Changes:
- Convert unlock_amount and supply to Number (from BigInt) before calculating projected apr
=> fix: convert on chain response to number from bigint before calc

apps/dao/src/store/createProposalsSlice.ts
Changes:
- Sort proposals on 'startDate' rather then 'voteId' to ensure parameter and ownership votes appear in correct order
=> fix: sort proposals on start date instead of voteId

apps/dao/package.json, apps/main/package.json, yarn.lock
Changes:
- Upgraded curve-js to 2.65.25 on /dao
- Upgraded curve-js to 2.65.25 on /main
=> chore: upgrade curve-js to 2.65.25 on /dao

packages/curve-ui-kit/src/shared/ui/DataTable.tsx, packages/curve-ui-kit/src/themes/design/1_surfaces_text.ts, packages/curve-ui-kit/src/themes/design/2_theme.ts
The table header did not have enough contrast in chad mode. This was fixed in the design system:
Before: 
After:
=> feat: new color of the table header in chad

apps/dao/package.json, apps/main/package.json, update-curve.sh, yarn.lock
- https://github.com/curvefi/curve-js/pull/438
- Add script that automated the creation of this PR
=> chore: update Curve dependencies

apps/loan/package.json, yarn.lock
- https://github.com/curvefi/curve-stablecoin-js/pull/29
=> chore: upgrade stablecoin-api to 1.5.8

apps/main/src/components/PageRouterSwap/Page.tsx, apps/main/src/components/PageRouterSwap/index.tsx, packages/curve-ui-kit/src/features/user-profile/store.ts
Advanced settings modal was incorrectly using the old "router" localstorage key to save slippage settings, while the rest of the front-end was relying on the more appropriately named "global" key.
=> fix: slippage not being set in advanced settings

apps/lend/src/components/PageLoanManage/LoanBorrowMore/components/DetailInfoLeverage.tsx
The wrong "expected" token symbol was being set when not in 'advanced' mode.
=> fix: set correct swapToSymbol in lend borrow more

apps/dao/package.json, apps/main/package.json, yarn.lock
- https://github.com/curvefi/curve-js/pull/440
=> chore: upgrade curvefi/api to 2.65.28 in /main and /dao

packages/curve-ui-kit/src/shared/routes.ts
- the disclaimer is moved to the footer
- now we can remove it from the menu
=> chore: remove disclaimer from menu

apps/main/src/dao/store/createAppSlice.ts, apps/main/src/dex/components/PageRouterSwap/utils.ts, apps/main/src/lend/store/createMarketListSlice.ts, packages/curve-ui-kit/src/features/switch-chain/ui/ChainSwitcher.tsx, packages/curve-ui-kit/src/lib/api/cache.ts, packages/curve-ui-kit/src/lib/logging.ts
- fixed missing `%c` in the format string
- escape %c in the data
- removed logs that were too long
- remove unused code
- export `LogStatus` for custom logging
=> fix: console logging

packages/curve-ui-kit/src/themes/design/2_theme.ts, packages/curve-ui-kit/src/themes/palette/palette.ts
- `02_theme.Feedback` was removed from the design system in favor of `02_theme.Layer.Feedback` and `02_theme.Text.TextColors.Feedback`
- This PR removes the old, now unused, theme variables
=> refactor: remove unused theme variables

packages/curve-ui-kit/src/shared/ui/Metric.tsx, packages/ui/src/utils/utilsConstants.ts, packages/ui/src/utils/utilsFormat.ts
- sometimes our APIs will return incorrect dollar values
- ideally we want to be warned about such errors; however, we don't yet have a mechanism for it
- for now, we'll just hide the values from the UI
=> feat: hide USD values > 100T

apps/main/src/dex/components/PageCreatePool/constants.ts
The current max in the pool implementation contract is 10**6: https://github.com/curvefi/stableswap-ng/blob/fd54b9a1a110d0e2e4f962583761d9e236b70967/contracts/main/CurveStableSwapNG.vy#L177
I propose we bump to 20,000 to allow for more concentrated pools from the pool creation component
current max:
=> bump max A to 20,000

packages/eslint-config-custom/index.js, packages/eslint-config-custom/package.json, yarn.lock
- install eslint plugin
- make sure the apps cannot import each other's code
=> chore: forbid cross-app imports

packages/curve-ui-kit/src/utils/searchText.ts
- the fuse search was configured to only match the beginning of the pool name
- by passing `ignoreLocation: true` we can also search later parts of the pool name
- Note that this will also change the way tokens are searched, e.g. 'usr' will return 'wstUSR' as the first match
=> fix: search any word in the pool name

apps/main/src/dao/components/PageAnalytics/CrvStats/index.tsx, apps/main/src/dao/components/PageAnalytics/DailyLocksChart/PositiveAndNegativeBarChart.tsx, apps/main/src/dao/components/PageAnalytics/HoldersTable/index.tsx, apps/main/src/dao/components/PageAnalytics/TopHoldersChart/TopHoldersBarChartComponent.tsx, apps/main/src/dao/components/PageUser/UserStats/index.tsx, apps/main/src/global-extensions.ts, apps/main/src/lend/store/createOhlcChartSlice.ts, apps/main/src/loan/store/createOhlcChartSlice.ts, packages/prices-api/src/chains/parsers.ts, packages/prices-api/src/crvusd/parsers.ts, packages/prices-api/src/dao/parsers.ts, packages/prices-api/src/gauge/parsers.ts, packages/prices-api/src/lending/parsers.ts, packages/prices-api/src/liquidations/parsers.ts, packages/prices-api/src/llamalend/parsers.ts, packages/prices-api/src/llamma/parsers.ts, packages/prices-api/src/ohlc/parsers.ts, packages/prices-api/src/pools/parsers.ts, packages/prices-api/src/proposal/parsers.ts, packages/prices-api/src/revenue/parsers.ts, packages/prices-api/src/savings/parsers.ts, packages/prices-api/src/timestamp.ts
* Turns out lightweight charts prefer to have the actual data adjusted to the local time zone as per https://tradingview.github.io/lightweight-charts/docs/time-zones#how-to-add-time-zone-support-to-your-chart.
* Adds `bigint.prototype.fromWei()` to easily convert bigints to a presentational number
* Renames 'toUTC' to 'toDate' such that the function's purposes is clearer
* Lodash doesn't have a suitable alternative for the `combinations` function we've implemented ourselves, so that has been kept untouched.
* Depends on https://github.com/curvefi/curve-frontend/pull/637
=> refactor: prices api minor feedback

apps/main/src/lend/components/DetailsMarket/components/MarketParameters.tsx, apps/main/src/loan/components/LoanInfoLlamma/LoanInfoParameters.tsx, packages/ui/src/Chart/CandleChart.tsx, packages/ui/src/Chart/ChartWrapper.tsx
Renames 'A' to 'Band width factor' for loans. Also fixed some casing and lightweight charts color issues. 
I thought it would be nice to add a tooltip explaining the band width factor, but couldn't get it to work nicely. Fixing this and replacing the tooltip component is outside the scope of this PR
=> fix: band width factor

apps/main/src/dex/components/PoolLabel.tsx
Removed "pool type label" from pools rows in pool list
Before:
After:
=> refactor: Remove TableCellReferenceAsset from PoolLabel

packages/curve-ui-kit/src/widgets/Disclaimer/Tabs/CrvUsd.tsx, packages/curve-ui-kit/src/widgets/Disclaimer/Tabs/Dex.tsx
- replace old links which directs to a page not found with new ones
=> Fix old links for audit and whitepaper tabs on risk disclaimer page

apps/main/src/dao/hooks/usePageOnMount.ts, apps/main/src/dao/layout/Header.tsx, apps/main/src/dex/hooks/usePageOnMount.ts, apps/main/src/dex/layout/default/Header.tsx, apps/main/src/lend/hooks/usePageOnMount.ts, apps/main/src/lend/layout/Header.tsx, apps/main/src/loan/hooks/usePageOnMount.ts, apps/main/src/loan/layout/Header.tsx
- fix 404 when navigating Curve DEX while connected to a chain that lend and crvusd markets are not currently available
- add a leading slash to all redirects so they work from anywhere
- add some warnings for unexpected cases
=> fix: network redirects

packages/eslint-config-custom/index.js
Update the ESLint rules to make sure we don't import incorrect files. For example for `dex` the rule is now:
```json
{
"target": [
"apps/main/src/dao",
"apps/main/src/app/dao",
"apps/main/src/lend",
"apps/main/src/app/lend",
"apps/main/src/loan",
"apps/main/src/app/loan"
],
"from": [
"apps/main/src/dex",
"apps/main/src/app/dex"
]
}
```
=> chore: add routes to eslint import rules

.github/workflows/prices-api.yaml
It seems "prepublishOnly": "yarn run build" in the package.json doesn't really work when executed through github actions, so the published package ends up missing its `dist` folder. I can't really test it properly until Github Actions runs this in prod.
=> chore: add missing yarn build step for prices api

packages/prices-api/package.json
forgot to bump version in the previous PR, oopsie
=> chore: bump prices-api to 1.0.1

apps/main/package.json, yarn.lock
- https://github.com/curvefi/curve-stablecoin-js/pull/31/
- https://github.com/curvefi/curve-stablecoin-js/pull/32/
- https://github.com/curvefi/curve-stablecoin-js/pull/33/
- https://github.com/curvefi/curve-stablecoin-js/pull/34/
- https://github.com/curvefi/curve-stablecoin-js/pull/35/
- https://github.com/curvefi/curve-stablecoin-js/pull/36
- https://github.com/curvefi/curve-stablecoin-js/pull/37
- https://github.com/curvefi/curve-stablecoin-js/pull/38
=> chore: bump @curvefi/stablecoin-api to 1.5.17

apps/main/package.json, yarn.lock
- https://github.com/curvefi/curve-js/pull/449
=> chore: bump curvefi/api to 2.66.8

apps/main/src/lend/components/CampaignRewardsRow.tsx, apps/main/src/loan/components/CampaignRewardsRow.tsx, apps/main/src/loan/components/PageLlamaMarkets/cells/MarketTitleCell/MarketBadges.tsx, apps/main/src/loan/components/TokenLabel.tsx, apps/main/src/loan/hooks/usePageOnMount.ts, apps/main/src/loan/store/createCampaignRewardsSlice.ts, apps/main/src/loan/store/useStore.ts, packages/external-rewards/src/README.md, packages/external-rewards/src/actions.json, packages/external-rewards/src/campaigns/Etherfi.json, packages/ui/src/CampaignRewards/types.ts
Changes:
- Added new option for field action, "loan", to campaign rewards for crvusd mint markets
- Added campaign rewards support for loan app
- Added weETH mint market data to Etherfi.json
=> feat: enable points for crvusd loans

apps/main/package.json, yarn.lock
Changes:
- Bumped @curvefi/lending-api to 2.5.6
=> chore: bump @curvefi/lending-api to 2.5.6

apps/main/src/dex/components/PagePool/index.tsx, apps/main/src/dex/components/PageRouterSwap/Page.tsx, apps/main/src/dex/components/PageRouterSwap/index.tsx, apps/main/src/dex/components/PageRouterSwap/types.ts, apps/main/src/dex/lib/curvejs.ts, apps/main/src/dex/utils/utilsSwap.ts, apps/main/src/lend/components/PageLoanCreate/LoanFormCreate/components/DetailInfoLeverage.tsx, apps/main/src/lend/components/PageLoanCreate/LoanFormCreate/index.tsx, apps/main/src/lend/components/PageLoanManage/LoanBorrowMore/components/DetailInfoLeverage.tsx, apps/main/src/lend/components/PageLoanManage/LoanBorrowMore/index.tsx, apps/main/src/lend/components/PageLoanManage/LoanRepay/components/DetailInfo.tsx, apps/main/src/lend/components/PageLoanManage/LoanRepay/index.tsx, apps/main/src/lend/components/PageLoanManage/LoanSelfLiquidation/index.tsx, apps/main/src/loan/components/PageLoanCreate/LoanFormCreate/components/DetailInfoLeverage.tsx, apps/main/src/loan/components/PageLoanCreate/LoanFormCreate/index.tsx, apps/main/src/loan/components/PageLoanCreate/Page.tsx, apps/main/src/loan/components/PageLoanManage/LoanDeleverage/index.tsx, apps/main/src/loan/components/PageLoanManage/LoanLiquidate/index.tsx, apps/main/src/loan/components/PageLoanManage/LoanSwap/index.tsx, packages/curve-ui-kit/src/features/user-profile/store.ts
Changes:
- Restore stableswap specific slippage settings for router swap routes that only use stableswap pools
=> fix: slippage management for stableswap routes in router swap

packages/curve-ui-kit/src/themes/chip/mui-chip.ts
Looking at the new llama market page filters I noticed the icons were too big, so I made them adjust to the chip size as per the Badge page on the Figma design. I'm using the sizes of the Badges page, as the sizes on Chips page look rather inconsistent.
=> feat: enhance Chip component with icon size support

apps/main/package.json, yarn.lock
- https://github.com/curvefi/curve-js/pull/450
=> chore: bump @curvefi/api to version 2.66.9

apps/main/src/dex/components/PageCreatePool/TokensInPool/SelectTokenButton.tsx, apps/main/src/dex/components/PagePool/Swap/index.tsx, packages/curve-ui-kit/src/features/select-token/SelectToken.stories.tsx, packages/curve-ui-kit/src/features/select-token/ui/TokenSelector.tsx, packages/curve-ui-kit/src/features/select-token/ui/modal/TokenList.tsx, packages/curve-ui-kit/src/features/select-token/ui/modal/TokenSelectorModal.tsx
Fixes three smol bugs that appear in edge cases. Brought back compact mode I removed earlier, turns it was a bad idea to make bake it in by default. Whenever you searched and you had only 1 result the entire modal would shrink in height. Oops!
=> fix: token selector bugs

apps/main/src/dex/components/PagePoolList/components/TableRow.tsx
1. crv rewards are enabled, but that means no other rewards are being shown
2. there are no crv rewards (yet?)
3. so you see nothing
In short, the ternary shouldn't have been a ternary
=> fix: other rewards are not shown if crv rewards are enabled

packages/curve-ui-kit/src/themes/checkbox/index.ts, packages/curve-ui-kit/src/themes/checkbox/mui-checkbox.tsx, packages/curve-ui-kit/src/themes/checkbox/override-checkbox.d.ts, packages/curve-ui-kit/src/themes/components.ts, packages/curve-ui-kit/src/themes/stories/Checkbox.stories.tsx
Very similar to the radio button PR. Adds some sizing, but also replaces the checkbox icons so we can style invert the colors when checked as per the Figma design.
=> feat: add MuiCheckbox component and related stories to curve-ui-kit

apps/main/src/app/crvusd/[network]/beta-markets/page.tsx, apps/main/src/app/crvusd/[network]/beta-markets/server-side-data.ts, apps/main/src/app/crvusd/[network]/markets/[collateralId]/collateral.utils.ts, apps/main/src/app/crvusd/server-side-data.ts, apps/main/src/app/dex/[network]/InjectServeSideData.tsx, apps/main/src/app/dex/[network]/compensation/page.tsx, apps/main/src/app/dex/[network]/create-pool/page.tsx, apps/main/src/app/dex/[network]/deploy-gauge/page.tsx, apps/main/src/app/dex/[network]/layout.tsx, apps/main/src/app/dex/[network]/pools.util.ts, apps/main/src/app/lend/[network]/markets/[market]/market-name.utils.ts, apps/main/src/app/lend/server-side.data.ts, apps/main/src/dex/store/createCacheSlice.ts, apps/main/src/instrumentation.ts, apps/main/src/server-side-data.ts
- Preload dex, lend and mint data in the background via the [instrumentation](https://nextjs.org/docs/app/building-your-application/optimizing/instrumentation) file
- Do not wait for that in the request cycle - if the data isn't ready, just omit it from the response and let the frontend retrieve it
- Refresh the data every 1 minute
=> chore: fetch server data in background

apps/main/src/dex/components/PageRouterSwap/Page.tsx
White instead of black. New mui button on a non-mui page so it's a one-off issue wrt colors that don't mesh well.
No longer black but white:
=> fix: slippage settings button on chad theme is unreadable

.github/dependabot.yml
Set up Dependabot for the repository by adding a new configuration file.
- Added a Dependabot configuration file
- Configured a weekly update schedule
- Specified packages to ignore for semver major updates.
=> chore: set up Dependabot

packages/curve-ui-kit/src/features/slippage-settings/ui/SlippageSettingsModal.tsx, packages/curve-ui-kit/src/shared/ui/ModalDialog.tsx
When you open the slippage settings modal, change it but discard and then re-open, the form values don't reset and it will show the discarded values even though you did not click 'Save'. This edge case was handled in the old modal but must've slipped my mind when re-implementing. It's only a cosmetic issue.
=> fix: update slippage settings modal to reset form values on reopen

.github/dependabot.yml, apps/main/package.json, packages/curve-ui-kit/package.json, packages/eslint-config-custom/package.json, yarn.lock
- group all minor updates in a single PR so it may be tested and merged at once.
- run updates once a month. Security-wise there needs to be a balance between updating too fast and too slow
- bundle dependabot updates
-  #800
-  #799
-  #798
-  #797
-  #796
-  #795
=> chore: dependabot groups and interval

apps/main/src/dex/components/PagePool/PoolDetails/ChartOhlcWrapper/PoolActivity.tsx, apps/main/src/dex/components/PagePool/PoolDetails/ChartOhlcWrapper/index.tsx, apps/main/src/lend/components/ChartOhlcWrapper/PoolActivity.tsx, apps/main/src/lend/components/ChartOhlcWrapper/index.tsx, apps/main/src/lend/store/createOhlcChartSlice.ts, apps/main/src/loan/components/ChartOhlcWrapper/PoolActivity.tsx, apps/main/src/loan/components/ChartOhlcWrapper/index.tsx, apps/main/src/loan/store/createOhlcChartSlice.ts, packages/prices-api/package.json, packages/prices-api/src/llamma/models.ts, packages/prices-api/src/llamma/parsers.ts, packages/prices-api/src/llamma/responses.ts
This was originally pushed in #775 but was reverted due to an error when a user tried repaying an sDOLA position.
I've tested locally to borrow, borrow with leverage, repay, borrow more, self liquidate using mock data in the sDOLA market without experiencing any issues so it seems to work ok.
Additional changes to #775:
- Map liquidation range charts lengths with oraclePriceData if ohlc data points are unavailable.
=> feat: allow ohlc endpoints to recieve only oracle price data

apps/main/src/app/api/dex/[network]/route.ts, apps/main/src/background.ts, apps/main/src/dao/components/PageVeCrv/Page.tsx, apps/main/src/dao/store/createAnalyticsSlice.ts, apps/main/src/dao/store/createGaugesSlice.ts, apps/main/src/dao/store/createProposalsSlice.ts, apps/main/src/dao/store/createUserSlice.ts, apps/main/src/dex/components/PageCreatePool/TokensInPool/SelectTokenButton.tsx, apps/main/src/dex/store/createCreatePoolSlice.ts, apps/main/src/dex/store/createDeployGaugeSlice.ts, apps/main/src/dex/store/createPoolsSlice.ts, apps/main/src/lend/utils/helpers.ts, apps/main/src/loan/lib/apiCrvusd.ts, apps/main/src/loan/store/createScrvUsdSlice.ts, apps/main/src/loan/utils/helpers.ts, packages/curve-ui-kit/src/features/select-token/SelectToken.stories.tsx, packages/curve-ui-kit/src/features/slippage-settings/SlippageSettings.stories.tsx, packages/curve-ui-kit/src/lib/logging.ts, packages/curve-ui-kit/src/shared/HashRouterRedirect.tsx, packages/curve-ui-kit/src/shared/ui/CopyIconButton.tsx, packages/curve-ui-kit/src/shared/ui/stories/Banner.stories.tsx, packages/curve-ui-kit/src/shared/ui/stories/SearchField.stories.tsx, packages/eslint-config-custom/index.js, tests/cypress/support/e2e.ts, tests/killHardhatNodes.js, tests/runHardhatNodes.js
- Forbid `console.log` so we can use it during debugging only
- Update existing `console.log` calls
- Errors are now warns
- Debugging statements are removed 
- The rest is changed to `console.info`
=> chore: forbid console.log

apps/main/package.json, yarn.lock
Changes:
- Bumped @curvefi/api to 2.66.12 https://github.com/curvefi/curve-js/pull/455
=> chore: bump @curvefi/api to 2.66.12

packages/prices-api/package.json, packages/prices-api/src/lending/parsers.ts, packages/prices-api/src/lending/responses.ts
Changes:
- Changed name oracle_pools > price_source_pools to reflect API changes
- Bumped @curvefi/prices-api to 1.1.1
=> chore: bump prices-api to 1.1.1 and update pool property names in responses

apps/main/src/lend/components/PageMarketList/components/TableRowViewContentTable/TableRow.tsx
The header keeps jumping when it's in the bottom edge of the page. We do not need the intersection observer here, there is no performance issue
=> fix: jumpiness in lend table

.github/workflows/ci.yaml
This should solve issues with the cache service (error 422) in the lint action
See https://github.com/actions/setup-node/issues/1275#issuecomment-2808800966
=> chore: update setup node action

apps/main/package.json, yarn.lock
Fixes mainnet LINK/stLINK-ng pool contract interactions. This is the pool that has its own LP token added as a gauge reward
=> chore: bump @curvefi/api 2.66.16

apps/main/package.json, yarn.lock
Changes:
- bumped curvefi/lending-api to 2.5.9 https://github.com/curvefi/curve-lending-js/pull/59/files
=> chore: bump lending-api to 2.5.9

apps/main/src/dex/components/PageRouterSwap/Page.tsx
- QuickSwap page was rendering too often in staging.
- Fixed by a simple useMemo
=> fix: endless loop quick swap

apps/main/src/dex/components/PageRouterSwap/index.tsx
- remove an old effect that didn't use to get triggered
- this effect caused the page to restart routing endlessly in some situations
=> fix: stop resetting swap

apps/main/src/dex/store/createGlobalSlice.ts
Restoring the following line:
https://github.com/curvefi/curve-frontend/blob/779b6e77cc0cc0eb30e9f3f27871506f3d96e91a/apps/main/src/dex/hooks/usePageOnMount.ts#L50
=> fix: sonic quick swap

apps/main/src/dao/components/PageGauges/GaugeListItem/index.tsx
Changes:
- Added fallback for internal link to gauge page when effective_address is unavailable
=> fix: dao gauge internal link fallback

apps/main/package.json, yarn.lock
Changes:
- Bumped curvefi/api to 2.66.20 https://github.com/curvefi/curve-js/pull/464
=> chore: bump curvefi/api to 2.66.20

packages/curve-ui-kit/src/shared/ui/ActionInfo.tsx
Adjust color to match new figma colors for previous value and its arrow
=> styling: use tertiary color for action info prev val and arrow

packages/curve-ui-kit/src/themes/stories/Select.stories.tsx
The PR only adds a storybook for the select component such that further development is a bit easier. The storybook has a simple use case and a more complex use case with multi-select and custom rendering based on the market filters on the llamalend beta market page.
**This PR does not modify the select component in any way, shape or form.**
It's merely the groundwork for future select button work. I think we need the create our own wrapper component for Mui's select component because of the different non-standard ways we often use it. For the token selector feature we use it as a button, for the market filters we render our own custom menu because of the theme inverter etc. But that's for later.
=> styling: add storybook for select component

apps/main/package.json, yarn.lock
Changes:
- Bumped curvefi/stablecoin-api to 1.5.20
=> chore: bump curvefi/stablecoin-api to 1.5.20

apps/main/src/dex/components/PagePool/PoolDetails/PoolParameters/index.tsx, apps/main/src/dex/components/PagePool/index.tsx
The basepool list is fetched on chain, requiring access to an RPC. In the Advanced tab it is only used to verify if a token is a basepool or not. In this PR this dependency is removed and the basepool token validation will only happen when a wallet is connected, allowing a user not yet connected to browse pool parameters freely.
Changes:
- Removed dependency of a fully loaded list of basepool in order to show the advanced tab (for pool parameters) on pool pages
=> refactor: remove dependency of an available basepool list for pool page advanced tab

README.md
- Domain is `crvusd.curve.fi` not `crvusd-curve.fi`
=> Fix crvUSD domain typo in README

apps/main/package.json, yarn.lock
Changes:
- Bumped curvefi/llamalend-api to 1.0.17 https://github.com/curvefi/curve-llamalend.js/pull/22
=> chore: bump curvefi/llamalend-api to 1.0.17

packages/curve-ui-kit/src/hooks/useLocalStorage.ts, packages/curve-ui-kit/src/shared/ui/Banner.tsx, packages/curve-ui-kit/src/shared/ui/DomainChangedBanner.tsx, packages/curve-ui-kit/src/shared/ui/GlobalBanner.tsx, packages/curve-ui-kit/src/shared/ui/ThemeProvider.tsx, tests/cypress/e2e/all/header.cy.ts
This pull request updates the `GlobalBanner` component in the `curve-ui-kit` package to include a new warning message about a domain change.
- Added a new `showDomainChangeMessage` condition to display a warning banner if the current date is before June 1, 2025. 
- This banner informs users about the domain change to `curve.finance` and includes links to the announcement and tweet.
=> feat: add warning banner for domain change

apps/main/src/app/.well-known/walletconnect.txt/route.ts, packages/curve-ui-kit/package.json, yarn.lock
For unknown reason the link provided by the wallet connect modal isn't working anymore. By updating wagmi (and viem) we get the latest wallet connect modal, which has recently undergone a major revision. Perhaps the issue is fixed by merely updating the wagmi package. I've also removed the `@wagmi/connectors` and `@wagmi/core` packages as they are not needed and dependencies of wagmi itself. I think we only pinned it because of Onboard issues
Wallet Connect modal also has gotten a new look:
=> chore: update wagmi and viem (and fix wallet connect)

packages/curve-ui-kit/src/shared/ui/TradingSlider.tsx, packages/curve-ui-kit/src/shared/ui/stories/TradingSlider.stories.tsx, packages/curve-ui-kit/src/themes/components/slider/mui-slider.ts
Special variant of the MUI slider primitive that adds a percentage input field and changes the background color of the slider. Will be part of the Large Input widget.
Note: did not add the vertical markers for 25%, 50% and 75%. Too much hassle atm and of very low importance.
=> feat: add trading slider widget

apps/main/src/dao/components/Countdown.tsx, apps/main/src/dao/components/PageProposal/ProposalHeader/index.tsx, apps/main/src/dao/components/PageProposals/Proposal/index.tsx, apps/main/src/dao/components/PageVeCrv/components/FormWithdraw.tsx
Changes:
- Renamed VoteCountdown to more generic Countdown
- Added endDate prop to Countdown (startDate adds 7 days to mimic a proposal vote period)
=> fix: withdraw end duration countdown

packages/curve-ui-kit/src/features/connect-wallet/ui/ConnectWalletIndicator.tsx, packages/curve-ui-kit/src/shared/ui/ActionInfo.tsx, packages/curve-ui-kit/src/shared/ui/DataTable/DataRow.tsx, packages/curve-ui-kit/src/shared/ui/DataTable/DataTable.tsx, packages/curve-ui-kit/src/shared/ui/DataTable/RotatableIcon.tsx, packages/curve-ui-kit/src/shared/ui/InvertOnHover.tsx, packages/curve-ui-kit/src/shared/ui/LargeTokenInput.tsx, packages/curve-ui-kit/src/shared/ui/ModalDialog.tsx, packages/curve-ui-kit/src/shared/ui/TokenIcon.tsx, packages/curve-ui-kit/src/utils/index.ts, packages/curve-ui-kit/src/utils/mui.ts, packages/curve-ui-kit/src/widgets/Header/HeaderLogo.tsx
Hodgepodge of a handful of review comments and own small commits that I don't want to clog the soft liquidation PR with. Mainly concerns action infos and the large token input.
The reason why I want to use `SystemStyleObject` for `sx` props consistently instead of `SxProps`, is because `SxProps` doesn't work  with if the object contains a function like `color: t => t.design.Colors[200]`. Functionally this change doesn't change anything, it's just a typescript thing and I don't want to re figure out the solution when SxProps isn't working properly. Rather be consistent.
=> fix: hodgepodge

packages/curve-ui-kit/src/themes/components/mui-alert.tsx
I noticed alerts weren't thicc enough. Turns out the borders are the default MUI 1px wide, when they should be 2px according to Figma.
=> styling: alert boxes should have a 2px border width

packages/curve-ui-kit/src/shared/ui/Balance.tsx, packages/curve-ui-kit/src/themes/components/button/mui-button.d.ts, packages/curve-ui-kit/src/themes/components/button/mui-button.ts, packages/curve-ui-kit/src/themes/stories/Button.stories.ts
Think I've been able to get rid of the `!important` by using `&.MuiButton-link` and `&.MuiButton-inline` instead.
I've decided to introduce the `inline` variant and keep it separate from the [existing mui](https://mui.com/material-ui/react-button/#text-button) `text` variant. The `text` variant is when you still want some of that spacing and padding, `inline` is for when you truly want a text 'button' inside a paragraph/typography.
Besides the `Balance` component, another use case (which is why I've decided to create the variant) is for the link inside the alert in pic below
=> styling: add inline button style and fix link variant specificity

apps/main/package.json, yarn.lock
Changes:
- Bumped curvefi/api to 2.67.6 https://github.com/curvefi/curve-js/pull/483
- Bumped curvefi/api to 6.67.5 https://github.com/curvefi/curve-js/pull/482
- Bumped curvefi/api to 6.67.4 https://github.com/curvefi/curve-js/pull/481
=> chore: bump curvefi/api to 2.67.6

apps/main/src/loan/components/PageCrvUsdStaking/Statistics/StatsStack.tsx, apps/main/src/loan/components/PageCrvUsdStaking/StatsBanner/index.tsx, apps/main/src/loan/components/PageCrvUsdStaking/UserPosition/index.tsx, apps/main/src/loan/components/PageLlamaMarkets/LlamaMarketExpandedPanel.tsx, apps/main/src/loan/components/PagePegKeepers/components/PegKeeperStatistics.tsx, packages/curve-ui-kit/src/shared/ui/Metric.tsx, packages/curve-ui-kit/src/shared/ui/stories/Metric.stories.ts
For the manage soft liquidation card we need to support multiple notionals underneath a metric:
By default, notionals are joined with ` + `. For the moment there's no support for further customization like custom joining and/or wrapping. That's a fight only worth fighting when it's an actual problem.
In order to support this, I've also flattened the options in both the main value and notionals. There's now a `ValueOptions` type, and
```typescript
/** A unit can be a currency symbol or percentage, prefix or suffix */
unit?: Unit | undefined
/** The number of decimals the value should contain */
decimals?: number
/** If the value should be abbreviated to 1.23k or 3.45m */
abbreviate?: boolean
/** Optional formatter for metric value */
formatter?: (value: number) => string
```
has been …
=> feat: multiple metric notionals

packages/curve-ui-kit/src/features/select-token/SelectToken.stories.tsx, packages/curve-ui-kit/src/features/select-token/blacklist.ts, packages/curve-ui-kit/src/features/select-token/ui/modal/TokenList.tsx, packages/curve-ui-kit/src/features/select-token/ui/modal/TokenOption.tsx
Because of regulatory concern regarding the A7A5 token (`0x0D57436F2d39c0664C6f0f2E349229483f87EA38`), we need a way to blacklist tokens in the token selection modal.
Because of its immediate nature, the scalability and centralized nature of this solution is not up to debate. A hardcoded blacklist is fine.
There’s three considerations to be made when implementing the blacklist:
1. Tokens should be disabled with a tooltip on hover, explaining they’re disabled specifically because they’re blacklisted. This is preferred over simply hiding the token, to prevent confusion and suggesting something might be broken on the UI.
2. ~~The blacklisted tokens should **not** be blacklisted when picking a “from” token when swapping. This gives users an opportunity to get out, such that they are not stuck …
=> feat: add blacklist and immediately blacklist a7a5

apps/main/src/dao/components/AlertFormError.tsx, apps/main/src/dex/components/AlertFormError.tsx
For some reason the DAO app has the same error but I don't think it's being used. Still updating it anyway because I don't want to FAFO
=> fix: update text when swap is not available

apps/main/src/lend/components/DetailInfoHealth.tsx, apps/main/src/lend/components/DetailsUser/components/DetailsUserLoanAlertSoftLiquidation.tsx, apps/main/src/lend/hooks/useTitleMapper.tsx, apps/main/src/lend/lib/apiLending.ts, apps/main/src/loan/components/DetailInfoHealth.tsx, apps/main/src/loan/components/LoanInfoUser/components/AlertSoftLiquidation.tsx, apps/main/src/loan/hooks/useTitleMapper.tsx, apps/main/src/loan/utils/utilsCurvejs.ts
There was some confusion as the label "hard liquidation" implies the loan has been hard liquidated. However, if a loan is actually hard liquidated it's actually closed so there is no loan to begin with. When a loan is in 'hard liquidation' mode, it just means there's a chance it might be hard liquidated by a liquidator somewhere in the future, unless the user manages to get its health > 0 before that occurs. Therefore, I suggest changing the label to 'hard liquidatable' instead to indicate the loan isn't actually closed yet.
PS: the amount of duplicated code for the tooltip that says ```{t`Hard liquidation may be triggered when health is 0 or below.`}{' '}``` is really nasty lol
=> fix: change 'hard liquidation' to 'hard liquidatable'

apps/main/src/app/layout.tsx
- configure turbopack to import the css file as a [global import](https://nextjs.org/docs/app/getting-started/css#global-css)
- the import should now load fine both in production and dev builds
=> fix: turbopack css import

apps/main/src/llamalend/PageLlamaMarkets/cells/RateCell/RateCell.tsx, apps/main/src/llamalend/PageLlamaMarkets/cells/RateCell/RewardsIcons.tsx
Round reward icon borders & arrow placement on borrow and lend rates is on the rates itself. I also tried to place the arrow for the utilization tooltip on the percentage value, but it's not possible as you want it also to show when hovering over the progress bar, which spans the entire cell)
=> styling: arrows and borders

apps/main/src/dex/components/PagePool/PoolDetails/PoolParameters/index.tsx, apps/main/src/dex/components/PagePool/PoolDetails/PoolStats/PoolParametersA.tsx
- [Pool page](https://www.curve.finance/dex/ethereum/pools/steth/deposit/) crashes when clicking on advanced tab
- That happens due to dayjs does not work with `ll` format when using the `en` locale: https://github.com/iamkun/dayjs/issues/2281
=> fix: crash on advanced tab

apps/main/src/app/ClientWrapper.tsx, apps/main/src/lend/layout/Settings.tsx, apps/main/src/loan/layout/Settings.tsx, apps/main/src/loan/store/createAppSlice.ts, packages/curve-ui-kit/src/features/layout/store.ts
Was broken with the refactor to `ClientWrapper.tsx`. Removed `scrollY` from the layout store as it was literally only used for the scroll button logic. When you haven't scrolled and the button is not visible it's still clickable, but didn't bother to fix that as I suspect this entire thing gets replaced in the future anyway, and it's non-breaking.
=> fix: scroll-up button was not visible yet clickable

apps/main/src/loan/components/LoanInfoUser/components/ChartUserBands.tsx, apps/main/src/loan/components/LoanInfoUser/components/ChartUserLiquidationRange.tsx, apps/main/src/loan/components/LoanInfoUser/components/UserInfoDebt.tsx, apps/main/src/loan/components/LoanInfoUser/components/UserInfoLiquidationRange.tsx, apps/main/src/loan/components/LoanInfoUser/components/UserInfoLlammaBalances.tsx, apps/main/src/loan/components/LoanInfoUser/components/UserInfos.tsx, apps/main/src/loan/components/LoanInfoUser/index.tsx, apps/main/src/loan/components/PageLoanManage/LoanDecrease/index.tsx, apps/main/src/loan/components/PageLoanManage/LoanDeleverage/index.tsx, apps/main/src/loan/hooks/useUserLoanDetails.ts
I've come to regret the decision I've made earlier last month. The DX is a lot better if you explicitly default to an empty object at the last possible moment, rather than at the top level.
For example:
`const { userState: { debtToken: { symbol } } } = useUserLoan() ?? {}` doesn't work, because you can't destructure further than one level deep. You'll get an error like 'debtToken' cannot be destructured from `undefined`. And worst of all, you get a typescript error that this is a possibility.
It's better to keep the type possibly undefined, and then chain with the elvis operator as such: `const { symbol } = useUserLoan()?.userState?.debtToken ?? {}`, which makes the type of `symbol: undefined | string` and eliminates the chance of a runtime error that typescript fails to detect.
=> refactor: dont default to empty object on undefined user details

apps/main/src/loan/components/LoanInfoUser/components/UserInfoLlammaBalances.tsx
You can't have `<li>` in `<li>`. Sometimes, almost randomly, NextJS complains about this in dev mode giving me a full screen error I can't click away and then I have to refresh. Very annoying.
=> fix: illegal li in li

apps/main/package.json, yarn.lock
Changes:
- bumped curve-js to 2.68.1 https://github.com/curvefi/curve-js/pull/487
=> chore: bump curve-js to 2.68.1

packages/curve-ui-kit/src/lib/model/entities/token-usd-rate.ts
Changes:
- Re-enabled deduplication in token-usd-rate after encountering warnings, previously removed in: https://github.com/curvefi/curve-frontend/pull/1154/commits/01d8e92e33cc3b80e9874fdfc17ac0603a75dbba
=> refactor: re-enable deduplication in token-usd-rate

apps/main/src/lend/components/DetailsMarket/components/DetailsContracts.tsx
Changes:
- Added 'controller' and 'amm' to displayed contracts in the supply section for lending markets
=> feat: show amm and controller addresses in supply

packages/curve-ui-kit/src/lib/model/entities/gas-info.ts
Networks might not yet be loaded, leading to an undefined network for a brief moment.
=> fix: undefined errors when fetching gas prices urls from network

apps/main/src/llamalend/PageLlamaMarkets/LendTableFooter.tsx, apps/main/src/loan/components/PageCrvUsdStaking/Statistics/AdvancedDetails.tsx, apps/main/src/loan/components/PageCrvUsdStaking/Statistics/index.tsx, apps/main/src/loan/components/PageCrvUsdStaking/UserPosition/index.tsx, packages/curve-ui-kit/src/themes/components/card-header/mui-card-header.ts, packages/curve-ui-kit/src/themes/components/index.ts, packages/curve-ui-kit/src/themes/components/mui-card-content.ts, packages/curve-ui-kit/src/themes/components/mui-card.ts, packages/curve-ui-kit/src/themes/stories/Card.stories.tsx
Depends on #1181
1. Add default cards styling
2. Updates card padding to be responsive and correct according to Figma
3. Cards have a default surface background color as per Figma
4. Improve margin between card header avatar and title itself
5. Add storybook stories that also shows how to use `<CardHeader>`, `<CardContent>` and `<CardActions>`
=> styling: cards

apps/main/src/llamalend/PageLlamaMarkets/cells/RateCell/LendRateTooltip.tsx
Removes empty rendering of staking incentives when there are none. Example would be optimism wsteth pool
=> fix: staking incentives being shown when there are none in tooltip

apps/main/src/lend/hooks/useBorrowPositionDetails.ts, apps/main/src/lend/hooks/useMarketDetails.tsx, apps/main/src/loan/hooks/useLoanPositionDetails.ts, apps/main/src/loan/hooks/useMarketDetails.ts, packages/curve-ui-kit/src/features/market-details/index.tsx, packages/curve-ui-kit/src/features/market-position-details/BorrowInformation.tsx, packages/curve-ui-kit/src/features/market-position-details/tooltips/CollateralMetricTooltip.tsx, packages/curve-ui-kit/src/features/market-position-details/tooltips/LiquidityThresholdMetricTooltip.tsx, packages/curve-ui-kit/src/features/market-position-details/utils.ts, packages/curve-ui-kit/src/shared/ui/Metric.tsx, packages/curve-ui-kit/src/shared/ui/SymbolCell.tsx
Changes:
- Set default decimals for Metric component to 2 (from 1)
- Fix "buffer to liquidation" calculation
- Fix collateral value tooltip wrapping issue
- Fix sidechain token icon src paths in SymbolCell
- Refactor liquidation threshold tooltip, rename notional value to "Distance to LT"
=> fix: market borrow position details fixes

apps/main/package.json, apps/main/src/app/GlobalLayout.tsx, yarn.lock
**Description:**
When navigating between pages, the current UI does not indicate that the next page is loading on the server.
This lack of feedback can cause users to think their click didn’t register, leading to multiple clicks or leaving the page, especially noticeable on the /llamalend page.
**Solution:**
Implemented a top-page progress bar to visually indicate loading state during page transitions. Using the project’s theme colors.
**Preview:**
https://github.com/user-attachments/assets/c3d6ab98-b11a-4c30-bb65-e6eca2514898
=> feat: top page progress bar loader

apps/main/src/lend/lib/apiLending.ts, apps/main/src/loan/utils/utilsCurvejs.ts
- The lazy import of the libraries is not used anymore, as the apps are imported directly in the ui-kit
- The code can be removed to avoid warnings
=> refactor: remove unused code

apps/main/src/dex/components/PageDashboard/components/TableHead.tsx, apps/main/src/dex/components/PagePool/PoolDetails/PoolStats/Rewards.tsx, apps/main/src/dex/components/PagePoolList/components/TableHead.tsx, apps/main/src/loan/components/PagePegKeepers/components/Footer.tsx
- fixed PSR footer to use consistent wording
- fixed Base vAPY tooltips by adding "Base" at the beginning
cute llama pic:
=> PSR Footer + Base vAPY Tooltip

apps/main/package.json, apps/main/src/dex/lib/networks.ts, yarn.lock
Changes:
- Bumped curvefi/api to 2.68.5 https://github.com/curvefi/curve-js/pull/491/files
- Add exception to networks config to show pool rewards apy on TAIKO
=> feat: enable pool rewards apy on TAIKO

.github/workflows/ci.yaml
- disable data collection for turbopack and IBM carbon packages
- these variables have also been added to vercel
- add them to your own machine if wished
=> chore: disable telemetry

apps/main/src/app/dao/layout.tsx
- This should allow the proposal list to show the loading state while the gauges are still being loaded
=> chore: render dao app before hydration is done

apps/main/src/lend/types/lend.types.ts, apps/main/src/lend/utils/utilsRouter.ts, apps/main/src/loan/types/loan.types.ts, apps/main/src/loan/utils/utilsRouter.ts
- the form type is expected to be `''` instead of `null` when rendering the form in [this line](https://github.com/curvefi/curve-frontend/blob/4f1b94dab23e9caeb9e667008705b2688643da4f/apps/main/src/lend/components/PageLoanCreate/index.tsx#L48)
=> fix: lend form type

packages/prices-api/package.json, packages/prices-api/src/chains/api.ts
Lots of the CurveMonitor website is broken atm because pagination was removed from the api for chain info
After merging this PR I'll need to update the curvemonitor website to use the new library version
=> fix: remove prices api pagination

packages/curve-ui-kit/src/themes/components/button/mui-button.ts, packages/curve-ui-kit/src/themes/components/button/mui-icon-button.ts
- IconButton sizes change the size of all svg, but the loading indicator gets larger than its container
=> fix: loading indicator

.github/workflows/ci.yaml
- restricts the ci job to change anything
=> chore: workflow permissions

apps/main/src/dao/components/PageGauge/GaugeMetrics/index.tsx
- fixes a crash when going directly to the [gauge page](https://www.curve.finance/dao/ethereum/gauges/0x156527deF9a2AB4F54C849575f23dC4BB439d9d9)
- the crash was caused by an invalid value `''` being passed to the `Date` object. That returns an invalid object that may not be used
=> fix: gauge page crash

.github/workflows/ci.yaml, .github/workflows/rpc-tests.yaml
- Enable RPC tests on main branch
- The project and account slugs aren't secrets, they can be passed via the `vars` context.
=> chore: enable component tests with RPC

apps/main/src/dex/components/PageCreatePool/ConfirmModal/CreateInfoLinkBar.tsx
- We were importing the svg from another project without the `?react` suffix
- It's better to use the shared [constant](https://github.com/curvefi/curve-frontend/blob/58a3c0100e96c53fba8baf9708bdc96652f60230/packages/ui/src/images/index.ts#L25)
=> fix: import correct svg

apps/main/src/llamalend/widgets/borrow/hooks/useMaxTokenValues.tsx, packages/curve-ui-kit/src/hooks/useTokenBalance.tsx
- avoid using parseInt as that's going to round off the user's balance
- create a hook to wrap useBalance and do the conversion properly so the code doesn't need to be repeated
- omit passing eth address to useBalance, as that causes an error (it's just for ERC-20 tokens)
=> fix: fractional and native token balances

packages/ui/src/utils/utilsConstants.ts
Before vs after:
Depends on https://github.com/curvefi/curve-assets/pull/929
=> fix: chad illustration background

.github/workflows/ci.yaml, .github/workflows/rpc-tests.yaml
- add an upload-artifact step to the RPC tests so we can examine the test failures
=> chore: export screenshots on RPC test failure

apps/main/src/lend/components/PageLoanCreate/index.tsx, apps/main/src/llamalend/features/borrow/components/BorrowTabContents.tsx, apps/main/src/llamalend/features/borrow/types.ts, apps/main/src/llamalend/llama.utils.ts, apps/main/src/loan/components/PageLoanCreate/index.tsx
- Get rid of the old create/leverage tabs in beta mode, only show the new borrow form
- Implement the new borrow form for lend markets, also in beta
- fix background issues with the tab switcher
=> feat: replace borrow tabs in beta mode

apps/main/src/llamalend/features/borrow/components/BorrowTabContents.tsx, apps/main/src/llamalend/features/borrow/useBorrowForm.tsx, apps/main/src/llamalend/llama.utils.ts
It's not part of the market object, so you're passing in data you already had to fetch elsewhere and is readily available.
Real reason is I want to use this function too without having to pass a chain name for no reason 😄 
Want to make it a pure `LlamaMarketTemplate` function
=> refactor: remove unused chain parameter from getTokens

apps/main/src/lend/hooks/useBorrowPositionDetails.ts, apps/main/src/lend/hooks/useSupplyPositionDetails.ts
Falling back on the API data is redundant and prone to confusion on the market page when a user has a wallet connected and is viewing a position.
Changes:
- Removes lend position details rates data api fallback
=> fix: remove lend position details rates data api fallback

apps/main/src/lend/components/PageLoanManage/LoanBorrowMore/index.tsx, apps/main/src/lend/components/PageLoanManage/LoanRepay/index.tsx
I know not too important but it bothered me. It's only temporary as cards get replaced in the future.
Gets rid of the stupid double borders
New
Old
=> fix: leverage input grouping lend

apps/main/src/llamalend/entities/llama-markets.ts, apps/main/src/loan/components/PageLoanCreate/Page.tsx, apps/main/src/loan/components/PageLoanCreate/index.tsx, apps/main/src/loan/components/PageLoanCreate/types.ts, apps/main/src/loan/components/PageLoanManage/Page.tsx, apps/main/src/loan/components/PageLoanManage/index.tsx, apps/main/src/loan/components/PageLoanManage/types.ts, apps/main/src/loan/types/loan.types.ts, apps/main/src/loan/utils/utilsRouter.ts, apps/main/src/routes/crvusd.routes.tsx
Depends on #1423 
Honestly the feature was already supported with #1423 where we decided to use the `useMintMarket` hook, which also maps controller addresses to mint market templates.
This PR basically just renames some variables such that it's more consistent with lending markets. And it changes the URL for mint market rows in the llamalend markets table.
=> feat: use mint market controller address in url instead of id

apps/main/src/dex/components/PagePool/Deposit/components/FormStake.tsx, apps/main/src/dex/components/PagePool/Withdraw/components/FormUnstake.tsx, apps/main/src/dex/components/PagePool/Withdraw/components/FormWithdraw.tsx, apps/main/src/dex/components/PagePool/components/FieldLpToken.tsx
The balance was being formatted and then converted to number again, that could not be parsed if LP was > 1k
=> fix: lp balance

apps/main/src/dex/hooks/usePoolAlert.tsx
An uppercase "A" was missed in the pool address for the yb-cbBTC pool, which prevented it from being properly flagged as withdraw only.
=> fixes uppercase in yb-cbBTC pool for warning 

apps/main/src/dex/store/createGlobalSlice.ts
This is a not so nice fix that solves the issue of networks not being always being available during dex hydration. I've tried multiple solutions, but this one is the only one that actually solves the issue. The issue is a high prio because of the Plasma launch, and having the Plasma pool pages broken is ugly.
The proper fix will be to refactor the dex networks store into a tanstack query, but due to time constraints that's not possible for now. I'll make a ticket for that.
=> fix: await networks in dex hydration to prevent async undefined networks

apps/main/package.json, yarn.lock
Changes:
- Bumped curvefi/api to 2.68.8 https://github.com/curvefi/curve-js/pull/494
=> chore: bump curvefi/api to 2.68.8

packages/curve-ui-kit/src/shared/ui/ModalDialog.tsx, packages/curve-ui-kit/src/widgets/Header/PhishingWarningModal.tsx
- remove close button and backdrop click
- the modal can only be closed with the button
- that is saved for the rest of the session
=> feat: remove phishing warning close button

apps/main/src/dex/components/PagePool/components/CampaignRewardsBanner.tsx, apps/main/src/lend/components/CampaignRewardsBanner.tsx, packages/ui/src/CampaignRewards/CampaignBannerComp.tsx
- #1446 must have changed the behavior to include empty lists of campaigns in the data set
- this PR handles empty list of campaigns by also checking the array length
=> fix: handle empty campaigns

apps/main/src/dex/components/PagePoolList/components/TableRowMobile.tsx
- fixes the volumes not loading automatically on mobile until a row is expanded
- Easy fix for this one. Added missing dependencies to `quickViewValue`, now the value will correctly update whenever the data loads
=> fix: missing dependencies in quickViewValue in mobile DEX table row

apps/main/src/llamalend/features/borrow/components/AdvancedBorrowOptions.tsx, apps/main/src/llamalend/features/borrow/components/LiquidationRangeSlider.tsx
Added "Max LTV" and "Safe" labels to the Liquidation range on the LLamalend Borrowing page
=> feat: "Max LTV" and "Safe" labels added to band slider

apps/main/package.json, yarn.lock
Changes:
- Bumped curvefi/api to 2.68.9 https://github.com/curvefi/curve-js/pull/495/files
=> chore: bump curvefi/api to 2.68.9

apps/main/src/dex/components/ChipPool.tsx, apps/main/src/dex/components/ChipToken.tsx, packages/ui/src/Spinner/Spinner.tsx
- Fixed the loading of the USD rate price for tokens in the DEX pool list.
- The price getter was not being triggered because we were checking the `formattedUsdRate`, which is set to "-" when no price is fetched. As a result, it wasn’t treated as a nullish value.
- Added `useCallback` to prevent unnecessary re-renders.
- Added the token address
- Squeezed in also the fix:horizontal XS spacing pool label address chip
=> fix: chip token USD rate loading indefinitely on hover
