curvefi/curve-frontend

- apps/loan/src/pages/_document.tsx
- apps/main/src/components/PagePool/PoolDetails/PoolInfo/PoolActivity.tsx
- apps/main/src/components/PagePool/PoolDetails/PoolInfo/TradesData.tsx
- apps/main/src/components/PagePool/PoolDetails/PoolInfo/index.tsx
- apps/main/src/pages/_document.tsx
- apps/main/src/store/createPoolsSlice.ts
- packages/ui/src/AlertBox/AlertBox.tsx
Changes:
- Fixed bug in AlertBox component
- Fixed mapping of token in pool activity/trades to map using event_index
> Task: Fix alert box bug, Fix pool activity token mapping

- apps/loan/src/layout/Footer.tsx
- apps/main/src/layout/default/Footer.tsx
updated footer links of main and loan page
> update footer links

- apps/main/package.json
- apps/main/src/components/PagePool/PoolDetails/PoolInfo/index.tsx
- apps/main/src/store/createPoolsSlice.ts
- packages/ui/src/Chart/CandleChart.tsx
- packages/ui/src/Chart/ChartWrapper.tsx
- packages/ui/src/Chart/utils.ts
- yarn.lock
Changes:
- Added horizontal refetch of historical OHLC data in the chart component
> Task: Add historical OHLC data refetch in chart component on horizontal scroll

- apps/main/package.json
- yarn.lock
changes:
- updated curvejs to 2.54.4 in /main
> chore: update curvejs to 2.54.4

- apps/main/src/components/PagePool/PoolDetails/PoolParameters/index.tsx
- apps/main/src/networks.ts
Changes:
- Added PayPool to base pools on mainnet in create-pool
- Added 3payLlama to base pools on mainnet in create-pool
- Added FRAXPYUSD to base pool on mainnet in create-pool
> Task: Add new base pools to Create Pool

- apps/main/package.json
- yarn.lock
changes:
- updated curvejs to 2.54.6
> chore: update curvejs to 2.54.6

- apps/main/package.json
- yarn.lock
Changes:
- Upgraded curve.js to 2.54.7
> Chore update curvejs to 2.54.7

- apps/main/package.json
- yarn.lock
Changes:
- Updated curve.js to 2.54.8
> chore: updated curve.js to 2.54.8

- apps/main/src/components/PageCreatePool/ConfirmModal/index.tsx
- apps/main/src/components/PageCreatePool/Parameters/InitialPrice.tsx
- apps/main/src/components/PageCreatePool/Parameters/index.tsx
- apps/main/src/components/PageCreatePool/SelectTokenModal/ComboBoxTokenPicker.tsx
- apps/main/src/components/PageCreatePool/Summary/OracleSummary.tsx
- apps/main/src/components/PageCreatePool/Summary/TokensInPoolSummary.tsx
- apps/main/src/components/PageCreatePool/TokensInPool/SelectToken.tsx
- apps/main/src/components/PageCreatePool/TokensInPool/SetOracle.tsx
- apps/main/src/components/PageCreatePool/TokensInPool/index.tsx
- apps/main/src/components/PageCreatePool/components/SwitchTokensButton.tsx
- apps/main/src/components/PageCreatePool/constants.ts
- apps/main/src/components/PageCreatePool/index.tsx
- apps/main/src/components/PageCreatePool/types.ts
- apps/main/src/components/PageCreatePool/utils.ts
- apps/main/src/networks.ts
- apps/main/src/store/createCreatePoolSlice.ts
Changes:
- Enabled 8 coin stableswap-ng pools in pool creation
- Disabled stableswap-ng basepools from pool creation (pyusd-usdc, pyusd-crvusd-frax, pyusd-frax)
> Task: Add 8 coin stableswap-ng pool support in pool creation

- apps/main/package.json
- apps/main/src/components/PageCreatePool/TokensInPool/index.tsx
- yarn.lock
Changes:
- Updated curvejs to 2.55.4
- Fixed 'add token' validation bug limiting token selection in some cases in create-pool
> Fix: token selection bug in create pool

- apps/main/src/components/PagePool/PoolDetails/PoolStats/index.tsx
- apps/main/src/components/PageRiskDisclaimer/Page.tsx
- apps/main/src/components/PageRiskDisclaimer/index.tsx
- apps/main/src/constants.ts
- apps/main/src/pages/index.tsx
- packages/ui/src/RiskDisclaimer/styles.ts
Changes:
- Added Curve LP risk disclaimer page on main app
> Task: Added curve LP risk disclaimer

- apps/main/src/components/PageDeployGauge/components/DeployGaugeButton.tsx
Changes:
- Fixed bug mixing up stableswap factories on deploy gauge action
> Fix: Fixed bug mixing up stableswap factories on deployment

- apps/loan/src/components/LoanInfoUser/components/UserInfoStats.tsx
- apps/loan/src/components/LoanInfoUser/index.tsx
- packages/ui/src/Tooltip/TooltipButton.tsx
> fix: loss tooltip not wrapping

- apps/main/src/components/PageCreatePool/constants.ts
Changes:
- Updated the Forex preset by increasing 'Gamma' by a factor of 10 and reducing 'A' by a factor of 10
- Lowered max 'A' by a factor of 10 in Cryptoswap pool creation
> task: update forex preset in pool creation

- apps/main/src/components/PageCreatePool/SelectTokenModal/ComboBoxTokenPicker.tsx
Changes:
- Fixed bug causing client to crash when search for new token in create-pool
> fix: fixed user added token search bug

- packages/onboard-helpers/package.json
- packages/onboard-helpers/src/index.ts
- packages/onboard-helpers/src/utils/walletModules.ts
- packages/ui/src/styles/layout.css
- yarn.lock
yarn.lock show installed @ledgerhq/connect-kit-loader v1.1.8, here's a screenshot for that package. It is not using a cdn anymore.
> task: add ledger back

- apps/loan/src/components/ChartBandBalances/index.tsx
- apps/loan/src/components/ChartOhlc/index.tsx
- apps/loan/src/components/LoanInfoLlamma/index.tsx
- apps/loan/src/components/LoanInfoUser/index.tsx
- apps/loan/src/components/PageLoanCreate/Page.tsx
- apps/loan/src/components/PageLoanManage/Page.tsx
- apps/loan/src/components/PoolInfoData/LiquidityData.tsx
- apps/loan/src/components/PoolInfoData/PoolActivity.tsx
- apps/loan/src/components/PoolInfoData/TradesData.tsx
- apps/loan/src/components/PoolInfoData/index.tsx
- apps/loan/src/components/PoolInfoData/types.ts
- apps/loan/src/components/PoolInfoData/utils.tsx
- apps/loan/src/store/createOhlcChartSlice.ts
- apps/loan/src/store/useStore.ts
- apps/main/src/components/PagePool/PoolDetails/PoolInfo/index.tsx
- apps/main/src/store/createPoolsSlice.ts
- packages/ui/src/Chart/CandleChart.tsx
- packages/ui/src/Chart/ChartWrapper.tsx
- packages/ui/src/Chart/DialogSelectChart.tsx
- packages/ui/src/Chart/DialogSelectChartContent.tsx
- packages/ui/src/Chart/DialogSelectTimeOption.tsx
- packages/ui/src/Chart/DialogSelectTimeOptionContent.tsx
- packages/ui/src/Chart/types.ts
- packages/ui/src/Chart/utils.ts
- packages/ui/src/Checkbox/Checkbox.tsx
- packages/ui/src/styles/palette.css
- packages/ui/src/styles/theme-default.css
Changes:
- Added chart support for crvusd
- Added oracle price line series
- Added volumes
- Added area series for liquidation ranges (new and current)
- Refactored chart component
> Task: Add charts to crvusd

- apps/lend/src/components/DetailsMarket/components/MarketParameters.tsx
- Add % to Fee, Admin Fee, Loan discount, Liquidation discount.
- fix significant digits
> fix: parameters percent updates

- apps/main/src/components/PageCreatePool/Parameters/index.tsx
- apps/main/src/components/PageCreatePool/Summary/ParametersSummary/CryptoswapParameters.tsx
- apps/main/src/components/PageCreatePool/constants.ts
- apps/main/src/store/createCreatePoolSlice.ts
Changes:
- Updated min-max parameter values for twocrypto factory pools in pool creation
- Removed 'initial price token order' warning in pool creation
- Added conversion to show at least 4 significant digits for calculated initial prices in pool creation
> Task: Update min max values for twocrypto in pool creation

- apps/lend/src/components/PageDisclaimer/Page.tsx
- packages/ui/src/Link/styles.ts
> task: lend update risk disclaimer

- apps/lend/src/components/DetailsMarket/components/DetailsSupply.tsx
- apps/lend/src/components/InpChipVaultShareUsdRate.tsx
- apps/lend/src/components/PageMarketList/components/TableRowViewContentTable/TableRow.tsx
- apps/lend/src/components/PageMarketList/components/TableRowViewContentTable/TableRowMobile.tsx
- apps/lend/src/components/PageMarketList/index.tsx
- apps/lend/src/components/SharedCellData/CellUserMain.tsx
- apps/lend/src/components/SharedCellData/CellUserVaultShares.tsx
- apps/lend/src/layout/Header.tsx
- apps/loan/src/components/PageMarketList/components/TableCellMarketsTotalDebt.tsx
- apps/loan/src/components/PageMarketList/components/TableStats.tsx
- apps/loan/src/layout/Header.tsx
- apps/main/src/layout/default/Header.tsx
- packages/ui/src/AppNav/AppNavPages.tsx
- packages/ui/src/AppNav/AppNavSecondary.tsx
- packages/ui/src/AppNav/index.ts
- packages/ui/src/AppNav/styles.ts
- packages/ui/src/AppNav/types.ts
- packages/ui/src/Brand/AppLogo.tsx
- packages/ui/src/HeaderStats/HeaderStats.tsx
- packages/ui/src/Select/Select.tsx
fix: laptop viewport size navbar
fix: change debt fraction to % of total supply
fix: vault shares to include gauge
> fix: nav bar laptop small

- apps/main/src/components/PageCreatePool/TokensInPool/index.tsx
Changes:
- Fixed token symbol not updating correctly in pool creation state changes
> Fix: Fixed token symbol not updating correctly in pool creation state changes

- apps/main/package.json
- yarn.lock
changes:
- updated curve-js to 2.56.9
> chore: update curvejs to 2.56.9

- apps/main/src/components/PageCreatePool/SelectTokenModal/ComboBoxTokenPicker.tsx
- apps/main/src/components/PageCreatePool/Summary/TokensInPoolSummary.tsx
- apps/main/src/components/PageCreatePool/TokensInPool/index.tsx
- apps/main/src/components/PageCreatePool/components/SwitchTokensButton.tsx
- apps/main/src/components/PageCreatePool/utils.ts
- apps/main/src/components/PagePool/PoolDetails/PoolParameters/index.tsx
- apps/main/src/networks.ts
- apps/main/src/store/createCreatePoolSlice.ts
- apps/main/src/store/createGlobalSlice.ts
- apps/main/src/store/createPoolsSlice.ts
- apps/main/src/types/global.d.ts
Changes:
- Refactored pool creation to use a dynamically fetched list of basepools via curve-js
> refactor: added dynamic basepool list fetching

- apps/lend/src/components/PageDisclaimer/Page.tsx
ahhhh i broke a link again. here is the fix.
> fix audits link

- apps/lend/package.json
- apps/lend/src/components/ChartBandBalances/index.tsx
- apps/lend/src/components/DetailsMarket/components/DetailsLoan.tsx
- apps/lend/src/components/DetailsMarket/styles.ts
- apps/lend/src/components/PageMarketList/Page.tsx
- apps/lend/src/components/PageMarketList/components/TableRowViewContentTable/TableRow.tsx
- apps/lend/src/components/PageMarketList/components/TableRowViewContentTable/TableRowMobile.tsx
- apps/lend/src/components/PageMarketList/index.tsx
- apps/lend/src/components/PageMarketList/types.ts
- apps/lend/src/components/SharedCellData/CellTotalCollateralValue.tsx
- apps/lend/src/layout/Header.tsx
- apps/lend/src/lib/apiLending.ts
- apps/lend/src/store/createAppSlice.ts
- apps/lend/src/store/createUsdRatesSlice.ts
- packages/ui/src/utils/utilsFormat.ts
- yarn.lock
Add Total Collateral Value
Hide summary if not in advanced mode
Fixed tbtc short market significant digits to 4
> task: add Total Collateral Value

- apps/main/src/store/createCreatePoolSlice.ts
Changes:
- Patched maExpTime conversion for twocrypto pool deployment
> task: patch maExpTime param for twocrypto deployment

- apps/main/src/components/PageCreatePool/SelectTokenModal/ComboBoxTokenPicker.tsx
- apps/main/src/components/PageCreatePool/TokensInPool/index.tsx
Changes:
- Added extra checks in case list of basepools hasn't been fetched
> fix: add extra checks in case list of basepools hasn't been fetched

- apps/main/src/networks.ts
Changes:
- Added tricrypto pool filters to all networks that has tricrypto
- Added crvusd pool filters to all networks with Lend
> task: Added tricrypto and crvusd filters

- apps/main/package.json
- apps/main/src/lib/curvejs.ts
- apps/main/src/store/createGasSlice.ts
- yarn.lock
Updated Arbitrum custom gas fee returned from getGasInfoForL2
> chore: upgrade curvejs 2.56.13

- apps/lend/package.json
- apps/lend/src/components/DetailsUser/components/DetailsUserLoan.tsx
- apps/lend/src/components/PageLoanCreate/LoanFormCreate/index.tsx
- apps/lend/src/components/PageLoanManage/LoanRepay/index.tsx
- apps/lend/src/components/PageLoanManage/LoanSelfLiquidation/index.tsx
- apps/lend/src/components/PageMarketList/components/TableRowViewContentTable/index.tsx
- apps/lend/src/components/SharedCellData/CellLoanState.tsx
- apps/lend/src/lib/apiLending.ts
- apps/lend/src/store/createGasSlice.ts
- apps/lend/src/store/createLoanRepaySlice.ts
- apps/loan/src/components/PageLoanManage/LoanDecrease/index.tsx
- apps/loan/src/components/PageLoanManage/LoanLiquidate/index.tsx
- apps/loan/src/store/createLoanDecreaseSlice.ts
- apps/main/src/globals.css
- packages/ui/src/AlertBox/AlertInfoSelfLiquidation.tsx
- packages/ui/src/AlertBox/index.ts
- packages/ui/src/DetailInfo/DetailInfo.tsx
- yarn.lock
- Update text from `AMM Position State, Collateral, Borrowed` to `Collateral Composition, Collateral symbol, Borrowed symbol`
- Add Self-liquidation information in Self-liquidate tab
- If loan exists, show `Your Details` tab first
- Update Lending Api to v1.6.7, apply same gas changes to Arbitrum network.
- Remove repay in full warning message
- Change `Manage Loan` in Create Loan page into a button
- Fixed width issue when there a pool requires seeding.
> fix: lending feedbacks

- apps/main/package.json
- apps/main/src/networks.ts
- yarn.lock
Changes:
- Updated curve-js to 2.56.14 on main
- Enabled tricrypto in pool creation on polygon
> Task: enable tricrypto in pool creation on polygon

- apps/main/src/store/createPoolsSlice.ts
Changes:
- Changed calculation for a tokens percentage share in a stableswap pool to use tokens balance in usd divided with total usd pool balance
> fix: percentage share in currency reserves fix for stableswap pools

- apps/main/package.json
- apps/main/src/components/PageDashboard/components/TableCellRewards.tsx
- apps/main/src/components/PagePool/Deposit/index.tsx
- apps/main/src/components/PagePool/PoolDetails/PoolStats/Contracts.tsx
- apps/main/src/components/PagePool/UserDetails/index.tsx
- apps/main/src/components/PagePool/Withdraw/components/FormClaim.tsx
- apps/main/src/components/PagePool/Withdraw/index.tsx
- apps/main/src/components/PagePoolList/components/TableRowMobile.tsx
- apps/main/src/components/PoolRewardsCrv.tsx
- apps/main/src/lib/curvejs.ts
- apps/main/src/store/createGasSlice.ts
- apps/main/src/store/createPoolListSlice.ts
- apps/main/src/store/createPoolsSlice.ts
- apps/main/src/types/global.d.ts
- yarn.lock
- upgrade curvejs v2.57.0, change **gaugeStatus** and **isGaugeKilled** to async calls
- upgrade curvejs v2.57.1, revert gas change on Arbitrum in UI, that code is in curvejs now.
> chore: upgrade curvejs 2.57.1

- apps/lend/src/components/PageDisclaimer/Page.tsx
- packages/ui/src/RiskDisclaimer/styles.ts
Update UI to make new changes from https://hackmd.io/@LlamaRisk/curve_lending_risk
> task: update lending disclaimer risk's crvusd risk section, refactor styles

- apps/main/src/components/PagePool/PoolDetails/PoolParameters/index.tsx
Changes:
- Fixed pool type information in advanced tab for old twocrypto pools
> fix: fixed pool type information in advanced tab for old twocrypto pools

- apps/main/package.json
- apps/main/src/store/createPoolsSlice.ts
- yarn.lock
Changes:
- Upgrade curve-js to 2.57.2
- Refactor fetchBasePools to be async
> Fix: fetch complete list of basepools dynamically

- apps/loan/src/components/CollateralLabel.tsx
- apps/main/src/components/PoolLabel.tsx
- apps/main/src/hooks/usePoolAlert.tsx
- Added Synthetix pool warning messages.
- Refactor mobile view alerts on pool list. Instead of an icon, it will show the alert below the label.
> task: add synthetix alert

- apps/lend/src/components/PageMarketList/components/TableRowViewContentTable/TableRowMobile.tsx
- apps/lend/src/components/PageMarketList/components/TableRowViewContentTable/index.tsx
- apps/lend/src/components/PageMarketList/types.ts
https://github.com/curvefi/curve-frontend/assets/6961602/73cd5393-fbe9-4706-884e-e67e879fc052
> fix: lend mobile view buttons

- apps/main/src/components/PagePool/PoolDetails/PoolStats/Rewards.tsx
- apps/main/src/components/PagePoolList/components/ChipVolatileBaseApy.tsx
- apps/main/src/components/PagePoolList/components/TableCellRewardsBase.tsx
- apps/main/src/constants.ts
> task: change base APY cap to 5000 and show warning if over cap

- apps/main/src/networks.ts
Changes:
- Enabled prices api on gnosis for charts, pool activity and snapshots data (advanced tab)
> task: enable prices api on gnosis

- apps/main/src/networks.ts
Changes:
- Added 'tricrypto' pool list filter on Gnosis network
> task: add tricrypto pool list filter on gnosis

- apps/loan/src/store/createOhlcChartSlice.ts
Changes:
- Removed formatting for amounts in fetched crvusd liquidity events data to adjust to changes made in the API data (formatting happens on the API)
> Fix adjust to crvusd events api formatting change

- apps/main/src/components/PagePool/PoolDetails/PoolParameters/index.tsx
Changes:
- Fixed bug causing a ghost 0 to sometimes appear in pool page's advanced tab
> fix: removed check that allowed a ghost 0 to sometimes appear on pool page's advanced tab

- apps/main/src/networks.ts
Changes:
- Disabled twocrypto pool creation on x-layer
> task: disable twocrypto pool creation on x-layer

- apps/main/src/networks.ts
> task: show X Layer in Select Network

- apps/lend/package.json
- apps/lend/src/components/PageLoanCreate/Page.tsx
- apps/lend/src/components/PageLoanManage/Page.tsx
- apps/lend/src/components/PageMarketList/Page.tsx
- apps/lend/src/components/PageMarketList/components/TableRowViewContentTable/TableRow.tsx
- apps/lend/src/components/PageMarketList/components/TableRowViewContentTable/TableRowMobile.tsx
- apps/lend/src/components/PageMarketList/components/TableSettings/TableSettings.tsx
- apps/lend/src/components/PageMarketList/index.tsx
- apps/lend/src/components/PageMarketList/types.ts
- apps/lend/src/components/PageVault/Page.tsx
- apps/lend/src/components/SharedCellData/CellMaxLeverage.tsx
- apps/lend/src/components/SharedCellData/CellToken.tsx
- apps/lend/src/components/SharedCellData/CellTotalCollateralValue.tsx
- apps/lend/src/components/TokenLabel.tsx
- apps/lend/src/constants.ts
- apps/lend/src/lib/apiLending.ts
- apps/lend/src/networks.ts
- apps/lend/src/store/createAppSlice.ts
- apps/lend/src/store/createLoanCreateSlice.ts
- apps/lend/src/store/createMarketListSlice.ts
- apps/lend/src/store/createMarketsSlice.ts
- apps/lend/src/types/global.d.ts
- yarn.lock
> chore: upgrade lending api 2.0.9

- apps/lend/package.json
- apps/lend/src/components/PageLoanCreate/Page.tsx
- apps/lend/src/components/PageLoanManage/Page.tsx
- apps/lend/src/components/PageMarketList/Page.tsx
- apps/lend/src/components/PageMarketList/components/TableRowViewContentTable/TableRow.tsx
- apps/lend/src/components/PageMarketList/components/TableRowViewContentTable/TableRowMobile.tsx
- apps/lend/src/components/PageMarketList/components/TableSettings/TableSettings.tsx
- apps/lend/src/components/PageMarketList/index.tsx
- apps/lend/src/components/PageMarketList/types.ts
- apps/lend/src/components/PageVault/Page.tsx
- apps/lend/src/components/SharedCellData/CellMaxLeverage.tsx
- apps/lend/src/components/SharedCellData/CellToken.tsx
- apps/lend/src/components/SharedCellData/CellTotalCollateralValue.tsx
- apps/lend/src/components/TokenLabel.tsx
- apps/lend/src/constants.ts
- apps/lend/src/lib/apiLending.ts
- apps/lend/src/networks.ts
- apps/lend/src/store/createAppSlice.ts
- apps/lend/src/store/createLoanCreateSlice.ts
- apps/lend/src/store/createMarketListSlice.ts
- apps/lend/src/store/createMarketsSlice.ts
- apps/lend/src/types/global.d.ts
- yarn.lock
Reverts curvefi/curve-frontend#193
> Revert "Revert "chore: upgrade lending api 2.0.9""

- apps/lend/src/components/AlertLoanSummary/components/SummaryPartial.tsx
- apps/lend/src/components/AlertLoanSummary/utils.ts
- apps/lend/src/components/PageLoanManage/LoanRepay/index.tsx
- apps/lend/src/lib/apiLending.ts
Repay with leverage form
Repay without leverage form
Fix summary digits display
> fix: broken repay

- apps/main/src/networks.ts
Changes:
- Enabled twocrypto pool creation on x-layer network
> task: enable twocrypto pool creation on x-layer

- apps/main/src/networks.ts
Changes:
- Enabled ohlc chart data from prices api on fraxtal
- Enabled pool activity data from prices api on fraxtal
> task: enable prices api on fraxtal for chart ohlc and pool activity data

- apps/main/src/components/PagePool/index.tsx
Changes:
-  Added check to ensure basepool list is loaded before allowing pool page advanced tab use
> fix: pool page advanced tab bug

- apps/lend/src/components/PageMarketList/components/TableRowViewContentTable/TableRow.tsx
- apps/lend/src/components/PageMarketList/components/TableRowViewContentTable/TableRowMobile.tsx
- apps/lend/src/components/PageMarketList/index.tsx
Add leverage column to Supply list:
> task: add leverage column to Supply list

- apps/main/src/components/PageCreatePool/constants.ts
Changes:
- Increase max gamma for tricrypto pool creation (from 0.02 to 0.05)
> task: increase max gamma for tricrypto pool creation

- apps/main/package.json
- yarn.lock
Changes:
- Upgraded curve-js to 2.60.1
> chore: upgrade curve-js to 2.60.1

- apps/main/src/components/PagePool/PoolDetails/PoolParameters/index.tsx
Changes:
- Fix formatting of offpeg fee multiplier in advanced tab to 1e10
> fix: formatting of offpeg fee multiplier in advanced tab to 1e10

- apps/lend/src/components/DetailInfoHealth.tsx
- apps/lend/src/lib/apiLending.ts
-use Health Full value for expected.
-use OraclePriceBand instead of ActiveBand to determine if user is closed to SL.
> fix: user expected health

- apps/main/package.json
- apps/main/src/components/PageDashboard/components/FormClaimFees.tsx
- apps/main/src/components/PageDashboard/components/FormClaimFeesButtons.tsx
- apps/main/src/components/PageDashboard/components/FormVecrv.tsx
- apps/main/src/components/PageDashboard/components/Summary.tsx
- apps/main/src/lib/curvejs.ts
- apps/main/src/store/createDashboardSlice.ts
- yarn.lock
> task: add claim crvUSD to dashboard

- packages/ui/src/CampaignRewards/CampaignBannerComp.tsx
- packages/ui/src/CampaignRewards/CampaignRewardsComp.tsx
- packages/ui/src/CampaignRewards/types.ts
Changes:
- Added custom banner messages for campaign reward types on pool page
> task: add custom banner messages for campaign reward types

- apps/main/src/components/PagePool/components/CampaignRewardsBanner.tsx
Changes:
- Fixed bug in CampaignRewardsBanner
> fix: fixed bug in banner CampaignRewardsBanner

- apps/lend/src/components/ChartOhlcWrapper/index.tsx
- apps/lend/src/store/createOhlcChartSlice.ts
Changes:
- Fixed response handling for ohlc chart api fetches when there is not yet any data
> fix: handle api returning detail for both ohlc chart types

- apps/main/package.json
- yarn.lock
Changes:
- Upgraded curve-js to 2.60.5
> chore: upgrade curvejs to 2.60.5

- apps/main/src/components/PagePool/Deposit/components/FormDeposit.tsx
- apps/main/src/components/PagePool/Deposit/components/FormDepositStake.tsx
- apps/main/src/components/PagePool/PoolDetails/PoolStats/index.tsx
- apps/main/src/components/PagePool/Swap/index.tsx
- apps/main/src/components/PoolLabel.tsx
- apps/main/src/hooks/usePoolAlert.tsx
- apps/main/src/types/global.d.ts
- Add notification and external link to Avalanche's Atricrypto pool regarding wBTC.e frozen asset
|Deposit form|Swap form|
|-------------|----------|
|<img width="403" alt="Screenshot 2024-07-08 at 7 44 52 AM" src="https://github.com/curvefi/curve-frontend/assets/6961602/38dd41a8-4183-41a0-a717-723131d83c55">|<img width="404" alt="Screenshot 2024-07-08 at 7 44 59 AM" src="https://github.com/curvefi/curve-frontend/assets/6961602/abbfcb41-5592-4b73-b438-76df3bda3d42">|
> task: add Avalanche Atricrypto wBTC.e notification

- apps/main/package.json
- apps/main/src/components/PagePool/PoolDetails/PoolParameters/index.tsx
- apps/main/src/components/PagePool/components/AddGaugeLink.tsx
- apps/main/src/store/createPoolsSlice.ts
- apps/main/src/types/global.d.ts
- yarn.lock
Changes:
- Upgraded curve-js to 2.61.1
> chore: upgrade curve-js to 2.61.1

- apps/main/package.json
- apps/main/src/store/createGasSlice.ts
- yarn.lock
Changes:
- Upgrade curve-js to 2.61.3
- Set same gas settings for Mantle as for X-Layer
> Task: mantle gas fix

- apps/main/package.json
- apps/main/src/components/PageCreatePool/SelectTokenModal/ComboBoxTokenPicker.tsx
- yarn.lock
Changes:
- Upgrade curve-js to 2.61.4
> chore: upgrade curve js to 2.61.4

- apps/main/package.json
- yarn.lock
Changes:
- Upgraded curve-js to 2.61.5
> chore: upgrade curve-js to 2.61.5

- apps/lend/package.json
- apps/lend/src/store/createCampaignRewardsSlice.ts
- apps/lend/tsconfig.json
- apps/main/package.json
- apps/main/src/store/createCampaignRewardsSlice.ts
- apps/main/tsconfig.json
- packages/external-rewards/.gitignore
- packages/external-rewards/package.json
- packages/external-rewards/pre-build.js
- packages/external-rewards/src/README.md
- packages/external-rewards/src/campaign-list.json
- packages/external-rewards/src/campaigns/DLCLink.json
- packages/external-rewards/src/campaigns/Eigenlayer.json
- packages/external-rewards/src/campaigns/Ethena.json
- packages/external-rewards/src/campaigns/Etherfi.json
- packages/external-rewards/src/campaigns/Kelpdao.json
- packages/external-rewards/src/campaigns/Mellow.json
- packages/external-rewards/src/campaigns/PufferFinance.json
- packages/external-rewards/src/campaigns/Renzo.json
- packages/external-rewards/src/campaigns/Symbiotic.json
- packages/external-rewards/src/campaigns/index.ts
- packages/external-rewards/src/index.ts
- packages/external-rewards/src/reward-tags.json
- packages/external-rewards/tsconfig.json
- turbo.json
Moved content from https://github.com/curvefi/curve-external-reward to /packages/external-rewards
> task: add campaign package

- packages/external-rewards/src/README.md
Changes:
- Updated external rewards section readme
> task: update external rewards README.md

- apps/lend/package.json
- apps/lend/src/components/DetailInfoPriceImpact.tsx
- apps/lend/src/lib/apiLending.ts
- yarn.lock
- show N/A if price impact is undefined, remove tooltip
> chore: upgrade lending api v2.1.1

- apps/main/src/components/PagePool/PoolDetails/PoolParameters/index.tsx
Changes:
- Refactor and ensure all pool types are shown in pool page's advanced tab
> fix: ensure all pool types are shown in pool page advanced tab

- apps/main/src/networks.ts
- apps/main/src/store/createGasSlice.ts
- packages/ui/src/utils/utilsNetworks.ts
- Add Mantle to select network dropdown, fix image asset url
- Show router page
> fix: Mantle config and gas

- apps/lend/src/layout/Footer.tsx
- apps/loan/src/layout/Footer.tsx
- apps/main/src/components/PageCreatePool/ConfirmModal/index.tsx
- apps/main/src/components/PagePool/components/AddGaugeLink.tsx
- apps/main/src/layout/default/Footer.tsx
Changes:
- Added link to branding materials to dapp footers
- Added footer link to crvhub
- Fixed a bug when linking to deploy gauge that sometimes selected the wrong twocrypto version
> Task: add branding footer link

- apps/main/src/components/PagePoolList/components/TableCellTvl.tsx
- apps/main/src/components/PagePoolList/components/TableCellVolume.tsx
- apps/main/src/components/PagePoolList/components/TableRow.tsx
- apps/main/src/components/PagePoolList/index.tsx
- apps/main/src/hooks/useCampaignRewardsMapper.tsx
- apps/main/src/hooks/useTokensMapper.tsx
- apps/main/src/hooks/useTokensNameMapper.tsx
- apps/main/src/layout/default/Header.tsx
- apps/main/src/networks.ts
- apps/main/src/store/createCacheSlice.ts
- apps/main/src/store/createPoolListSlice.ts
- apps/main/src/store/createPoolsSlice.ts
- apps/main/src/store/createTokensSlice.ts
- apps/main/src/store/useStore.ts
- apps/main/src/types/global.d.ts
> task: add native and wrapped native to router swap for all chains

- packages/external-rewards/package.json
- packages/external-rewards/src/campaign-list.json
- packages/external-rewards/src/campaigns/Eigenlayer.json
- packages/external-rewards/src/campaigns/YieldNest.json
Adding YieldNest protocol with a points campaign for ynETH / wstETH pool.
> Add yieldnest

- apps/lend/src/networks.ts
- apps/lend/src/store/createMarketsSlice.ts
- apps/lend/src/types/global.d.ts
Hide incorrect pool from USD0USD0++
> task: hide one-way-market-19 from lend list

- apps/lend/src/components/ChartOhlcWrapper/index.tsx
- apps/lend/src/store/createOhlcChartSlice.ts
Changes:
- Set lend chart titles from fetched pool data for pool data chart
> task: set lend chart titles from fetched pool data for pool data chart

- apps/lend/src/components/ChartOhlcWrapper/index.tsx
Changes:
- Added fallback data for liq range prices for OHLC chart liq range in Lend
> fix: add fallback data for liq range prices in ohlc chart in lend

- packages/external-rewards/src/campaigns/YieldNest.json
Increase the boost rate and update the campaign start/end time.
> YieldNest - Increase boost rate and update time.

- apps/lend/src/store/createCampaignRewardsSlice.ts
- apps/main/src/store/createCampaignRewardsSlice.ts
Changes:
- Added a network filter for external rewards campaign pools/markets
> fix: added network filter for external rewards

- apps/lend/src/store/createCampaignRewardsSlice.ts
- apps/main/src/store/createCampaignRewardsSlice.ts
Changes:
- Only create campaign rewards pool/market object exists on current network
> fix: fixed external rewards banner bug

- apps/loan/src/layout/Header.tsx
- apps/loan/src/store/createAppSlice.ts
Add Daily Volume to crvUSD app
> task: add daily volume to crvusd

- apps/main/src/components/PagePoolList/components/TableCellRewardsBase.tsx
- apps/main/src/components/PagePoolList/components/TooltipBaseApy.tsx
- packages/ui/src/utils/utilsFormat.ts
- Fixed missing % on negative apy
> fix: missing percent % for negative number

- apps/main/src/store/createPoolListSlice.ts
- Show aUSD₮ search result when searching aUSDT
> task: add ₮ option when searching for aUSD₮

- apps/main/src/components/PageCreatePool/Parameters/SelectPreset.tsx
- apps/main/src/components/PageCreatePool/constants.ts
Changes:
- Added LRT preset for stableswap pools in pool creation
> task: added LRT stableswap preset

- apps/main/src/components/PageRouterSwap/components/DetailInfoTradeRouteRoute.tsx
- packages/ui/src/TextEllipsis/TextEllipsis.tsx
> fix: router swap pool's name overflow

- apps/lend/src/store/createAppSlice.ts
- apps/main/src/store/createGlobalSlice.ts
Changes:
- Reset campaign rewards store on network change
> fix: reset campaign rewards store on network change

- apps/main/src/store/createPoolsSlice.ts
- apps/main/src/types/global.d.ts
- If isCrypto=true use USD balance to calculate %, if false use token balance to calculate %
> fix: use USD to calculate balance % for isCrypto pools only

- packages/ui/src/Chart/CandleChart.tsx
Changes:
- Added custom number formatting for all liquidation range series in the ohlc chart component to fix edge case price scale bug.
> fix: add custom number formatting to all chart series

- apps/main/src/components/PageCreatePool/TokensInPool/SetOracle.tsx
- apps/main/src/components/PageCreatePool/components/WarningBox.tsx
Changes:
- Added additional information to inform users creating pools with tokens of asset type oracle need to have an oracle with a precision of 18 decimals.
> task: add oracle precision information at add oracle token in pool creation

- apps/main/src/components/PagePool/PoolDetails/ChartOhlcWrapper/index.tsx
- apps/main/src/store/createPoolsSlice.ts
Changes:
- Changed default ohlc chart to USD denominated LP price from token0 denominated LP price in /main (DEX)
> task: change default pool chart option to LP/usd from LP/token0

- apps/main/package.json
- apps/main/src/components/PagePool/Deposit/components/FormDeposit.tsx
- apps/main/src/components/PagePool/Deposit/components/FormDepositStake.tsx
- apps/main/src/components/PagePool/Deposit/components/FormStake.tsx
- apps/main/src/components/PagePool/Swap/index.tsx
- apps/main/src/components/PagePool/Withdraw/components/FormClaim.tsx
- apps/main/src/components/PagePool/Withdraw/components/FormUnstake.tsx
- apps/main/src/components/PagePool/Withdraw/components/FormWithdraw.tsx
- apps/main/src/components/PagePool/components/AlertSeedAmounts.tsx
- apps/main/src/components/PagePool/components/TransferActions.tsx
- apps/main/src/components/PagePool/index.tsx
- apps/main/src/components/PagePool/types.ts
- apps/main/src/lib/curvejs.ts
- apps/main/src/store/createPoolDepositSlice.ts
- apps/main/src/store/createPoolsSlice.ts
- apps/main/src/types/global.d.ts
- packages/ui/src/utils/utilsFormat.ts
- yarn.lock
- refactor seed pool message and amounts with new getSeedAmounts method.
- removed factory label from pool page.
> chore: upgrade curvejs 2.63.4

- apps/main/src/components/PageCreatePool/index.tsx
Changes:
- Updated urls for pool creation curve resources links
> task: update curve resources pool creation links

- apps/lend/src/hooks/usePageOnMount.ts
- apps/loan/src/hooks/usePageOnMount.ts
- apps/main/src/hooks/usePageOnMount.ts
Reverts curvefi/curve-frontend#363
> Revert "fix: wallet connect"

- apps/lend/src/hooks/usePageOnMount.ts
- apps/loan/src/hooks/usePageOnMount.ts
- apps/main/src/hooks/usePageOnMount.ts
Reverts curvefi/curve-frontend#361
> Revert "fix: wallet connect useEffect"

- apps/main/src/store/useStore.ts
- Fix condition when to save cache
- Add warning when the cache is too large
> fix: maximum cache size

- apps/main/src/components/PagePool/PoolDetails/PoolStats/Rewards.tsx
Changes:
- Updated vAPY learn more link URL on pool page
> task: update vAPY learn more link

- apps/main/src/store/createPoolsSlice.ts
Changes:
- Fixed a bug when fetching more chart data to flip to token0 from USD denominated LP token prices
> fix: fetch more chart data bug

- .github/workflows/lint.yaml
- packages/curve-lib/package.json
- packages/external-rewards/package.json
- packages/ui/package.json
- yarn.lock
- Create a workflow to run `yarn lint` automatically on every push
- Add eslint dependency to libraries (see https://github.com/yarnpkg/berry/issues/1875#issuecomment-698670174)
> chore: lint in GitHub actions

- packages/external-rewards/src/campaigns/Eigenlayer.json
remove ynETH/wstETH pool from Eigenlayer campaign
> Update Eigenlayer pools

- apps/main/package.json
- yarn.lock
Changes:
- Upgraded curve-js to 2.63.10 on main
> chore: upgrade curve-js to 2.63.10 on main

- apps/lend/package.json
- apps/loan/package.json
- apps/main/package.json
- package.json
- packages/curve-lib/package.json
- packages/eslint-config-custom/package.json
- packages/onboard-helpers/package.json
- packages/ui/package.json
- yarn.lock
- use same `react` and `react-dom` versions in the dapp
> build: sync `react` versions

- apps/loan/src/components/PagePegKeepers/Page.tsx
- apps/loan/src/components/PagePegKeepers/index.tsx
- apps/loan/src/constants.ts
> task: add USDM to pegKeepers

- packages/external-rewards/src/campaigns/Mellow.json
- packages/external-rewards/src/campaigns/Renzo.json
- packages/external-rewards/src/campaigns/Symbiotic.json
> Update Renzo multipliers/pools 

- apps/loan/src/components/PageCrvUsdStaking/UserPositionBanner/index.tsx
- apps/loan/src/components/PageCrvUsdStaking/index.tsx
Changes:
- Fixed user scrvusd share calculation
- Removed signer address dependancy blocking yield api call
> fix: fixed user scrvusd share calc

- apps/lend/src/components/SharedPageStyles/PageTitleBorrowSupplyLinks.tsx
- apps/loan/src/components/PageCrvUsdStaking/StatsBanner/index.tsx
- apps/loan/src/components/PageCrvUsdStaking/UserInformation/index.tsx
- apps/loan/src/components/PageCrvUsdStaking/UserPositionBanner/index.tsx
- apps/loan/src/components/PageLoanCreate/Page.tsx
- apps/loan/src/components/PageLoanManage/Page.tsx
- apps/loan/src/store/createScrvUsdSlice.ts
- apps/loan/src/store/types.ts
- apps/main/src/components/PagePool/components/CampaignRewardsBanner.tsx
- apps/main/src/components/PagePool/index.tsx
- packages/ui/src/AppPage/styles.ts
Changes:
- Changed scrvusd yield data endpoint
- Made styling changes related to removal of background image
> Task: update scrvusd yield data endpoint

- apps/loan/src/components/PageCrvUsdStaking/StatsBanner/index.tsx
Changes:
- Removed apy multiplier in scrvusd banner
> fix: removed apy multipler in scrvusd banner

- packages/ui/src/AppNav/styles.ts
- packages/ui/src/styles/theme-chad.css
- packages/ui/src/styles/theme-dark.css
- packages/ui/src/styles/theme-default.css
Changes:
- Adjusted background color and header colors to improve contrast
> task: adjust background colors

- packages/ui/src/styles/theme-default.css
Updates Light Theme colours so that the updated nav doesn't clash with the old colours no more.
> Temporary color adjustment

- apps/lend/package.json
- apps/loan/package.json
- apps/main/package.json
- apps/main/src/store/createGlobalSlice.ts
Changes:
- Added basepool list fetch on newtorks with empty pool lists (needed for pool creation)
- Removed node version asserts for all dapps package.json
> fix: added basepool list fetch on networks with empty pool lists

- apps/lend/src/layout/index.tsx
- apps/loan/src/layout/index.tsx
- apps/main/src/layout/default/index.tsx
Merge main changes into develop. Includes:
- #466
> chore: update develop branch

- packages/curve-common/src/features/switch-chain/ui/ChainSwitcher.tsx
- packages/curve-common/src/widgets/Header/HeaderLogo.tsx
- packages/curve-common/src/widgets/Header/MenuToggleButton.tsx
- packages/curve-common/src/widgets/Header/MobileHeader.tsx
- packages/curve-common/src/widgets/Header/SideBarFooter.tsx
- packages/curve-common/src/widgets/Header/SidebarItem.tsx
- packages/curve-common/src/widgets/Header/SidebarSection.tsx
- packages/curve-ui-kit/src/themes/button/mui-icon-button.ts
- packages/curve-ui-kit/src/themes/typography/create-typography.ts
- packages/curve-ui-kit/src/themes/typography/mui-typography.ts
- tests/cypress/e2e/all/header.cy.ts
Depends on https://github.com/curvefi/curve-frontend/pull/472
> fix: layout paddings

- apps/main/package.json
- yarn.lock
This reverts commit 3160dfcbbc0ea2aef0e49e5d6162eca117765e12, reversing changes made to cad8dd44d079d29ee75389409b80473032fa70b9.
> Revert "Merge pull request #485 from curvefi/chore/curvejs"

- packages/ui/src/styles/theme-default.css
Changes:
- Fixed button border styling bug on hover
> styling: fix button on hover border styling

- apps/lend/src/components/PageMarketList/index.tsx
- apps/lend/src/hooks/useSearchTermMapper.tsx
- apps/lend/src/store/createMarketListSlice.ts
Changes:
- Fix SEARCH_TERM enum formatting to match data object
> fix SEARCH_TERM enum formatting to match data object

- apps/dao/src/store/createProposalsSlice.ts
Changes:
- Added api call to refresh proposal data after successful execute proposal action
> task: added refresh proposal data call after execute proposal action

- apps/main/src/components/ComboBoxSelectToken/ComboBoxSelectedToken.tsx
- packages/ui/src/Typography/Chip.tsx
> feat: use normal font for address chip

- apps/main/src/components/ComboBoxSelectToken/ComboBoxSelectedToken.tsx
- packages/ui/src/AppPage/styles.ts
Changes:
- Fix collapsing loan box by restoring input width values
> fix: restore missing loan input width value

- apps/dao/src/components/PageAnalytics/CrvStats/index.tsx
Changes:
- Fixed veCRV apr calculation bug in dao analytics
> fix: apr calculation bug

- packages/ui/src/styles/layout.css
This should bring them closer to the default mui z-indexes: https://mui.com/material-ui/customization/z-index/
> fix: increase z-indexes for older components

- apps/dao/package.json
- apps/lend/package.json
- apps/loan/package.json
- apps/main/package.json
- yarn.lock
- internal packages should still be added to the dependencies (see [internal packages docs](https://turbo.build/repo/docs/core-concepts/internal-packages))
> chore: add missing dependencies

- apps/dao/package.json
- apps/main/package.json
- yarn.lock
- https://github.com/curvefi/curve-js/pull/432
> chore: update curve-js to 2.65.21

- .husky/pre-commit
- package.json
- packages/curve-common/src/features/switch-chain/ui/ChainList.tsx
- packages/curve-ui-kit/src/themes/mui-switch.ts
- It was not visible when the switch was focused
- The switch state can be changed by pressing the spacebar
- fix the lint-staged config so simple formatting issues do not happen
> fix: focused switch, lint-staged config

- apps/dao/package.json
- apps/main/package.json
- yarn.lock
- https://github.com/curvefi/curve-js/pull/433
> chore: update curvejs to 2.65.22

- apps/lend/package.json
- apps/lend/src/components/DetailInfoLeverageAdvancedExpected/components/ExpectedSwapDetails.tsx
- apps/lend/src/components/DetailInfoLeverageAdvancedExpected/index.tsx
- apps/lend/src/components/DetailInfoLeverageAdvancedExpected/types.ts
- apps/lend/src/components/PageLoanCreate/LoanFormCreate/components/DetailInfoLeverage.tsx
- apps/lend/src/components/PageLoanCreate/types.ts
- apps/lend/src/components/PageLoanManage/LoanBorrowMore/components/DetailInfoLeverage.tsx
- apps/lend/src/components/PageLoanManage/LoanBorrowMore/types.ts
- apps/lend/src/components/PageLoanManage/LoanRepay/components/DetailInfo.tsx
- apps/lend/src/components/PageLoanManage/LoanRepay/types.ts
- apps/lend/src/lib/apiLending.ts
- apps/lend/src/types/global.d.ts
- apps/loan/package.json
- yarn.lock
- update lending js: https://github.com/curvefi/curve-lending-js/pull/44
- change routing details to show a the received image
> chore: switch to odos for llamalend leverage

- apps/dao/package.json
- apps/main/package.json
- yarn.lock
- https://github.com/curvefi/curve-js/pull/435
> chore: curvejs 2.65.23

- packages/curve-ui-kit/src/themes/button/mui-button.ts
- packages/curve-ui-kit/src/themes/design/1_sizes_spaces.ts
- The font-weight should not be responsive depending on the screen size
> fix: mui font weight

- apps/main/package.json
- tests/cypress/e2e/loan/llamalend-markets.cy.ts
- yarn.lock
- https://github.com/curvefi/curve-lending-js/pull/41
- https://github.com/curvefi/curve-js/pull/431
> chore: update curve-js and curve-lending-js

- apps/main/package.json
- apps/main/src/dex/components/PagePoolList/index.tsx
- apps/main/src/dex/hooks/usePageOnMount.ts
- apps/main/src/dex/store/createPoolsSlice.ts
- apps/main/src/dex/utils/utilsCurvejs.ts
- yarn.lock
- update to use https://github.com/curvefi/curve-js/pull/428
- show pool list without rpc
- initialize curve-js with `NoRPC` option
> feat: show pool list without rpc

- packages/external-rewards/src/campaigns/Kelpdao.json
- update campaign name
- update platform image id
> External rewards: update Kelp DAO campaign

- packages/curve-ui-kit/src/features/connect-wallet/ui/ConnectWalletPrompt.tsx
- connect wallet is making mobile screens scroll horizontally
- fixed by applying a maxWidth of 90vw
> fix: connect wallet for mobile screens

- apps/main/src/pages/dex.tsx
- the dashboard seems to have been removed in #650
> fix: restore dashboard route

- packages/curve-ui-kit/src/widgets/Footer/Sections.tsx
> feat: add api status page link to footer

- apps/main/src/global-extensions.ts
- apps/main/src/lend/store/createOhlcChartSlice.ts
- apps/main/src/loan/store/createOhlcChartSlice.ts
- apps/main/src/pages/_app.tsx
- packages/prices-api/src/fetch.ts
- packages/prices-api/src/lending/api.ts
- packages/prices-api/src/lending/models.ts
- packages/prices-api/src/lending/parsers.ts
- packages/prices-api/src/lending/responses.ts
- packages/prices-api/src/llamma/api.ts
- packages/prices-api/src/llamma/models.ts
- packages/prices-api/src/llamma/parsers.ts
- packages/ui/src/Chart/types.ts
> refactor: use prices api for llamma ohlc

- apps/main/package.json
- yarn.lock
- https://github.com/curvefi/curve-lending-js/pull/46
> chore: upgrade curvefi/lending-api

- apps/main/package.json
- update-curve.sh
- yarn.lock
- Update Curve API dependencies
- https://github.com/curvefi/curve-js/pull/442
- https://github.com/curvefi/curve-lending-js/pull/47
- https://github.com/curvefi/curve-lending-js/pull/48
- https://github.com/curvefi/curve-stablecoin-js/pull/30
- Fix auto-update script
> chore: update Curve dependencies

- apps/main/src/lend/components/DetailInfoPriceImpact.tsx
- apps/main/src/lend/lib/apiLending.ts
Changes:
- Allow price impact to show negative values
- Show error messages from all failed fetches in detailInfoLeverage
> fix: lend repay error handling

- apps/main/package.json
- yarn.lock
- https://github.com/curvefi/curve-lending-js/pull/49/
> chore: upgrade curvefi/lending-api to 2.4.5

- apps/main/src/lend/components/ChartOhlcWrapper/LiquidityData.tsx
- apps/main/src/lend/components/ChartOhlcWrapper/types.ts
- apps/main/src/lend/store/createOhlcChartSlice.ts
- apps/main/src/loan/components/ChartOhlcWrapper/LiquidityData.tsx
- apps/main/src/loan/components/ChartOhlcWrapper/types.ts
- apps/main/src/loan/store/createOhlcChartSlice.ts
- packages/prices-api/src/llamma/api.ts
- packages/ui/src/Chart/types.ts
>  refactor: use prices api for llamma events

- apps/main/src/dex/components/ComboBoxSelectToken/index.tsx
- apps/main/src/dex/components/PageCreatePool/SelectTokenModal/ComboBoxTokenPicker.tsx
- apps/main/src/dex/store/createSelectTokenSlice.tsx
- apps/main/src/loan/components/PageLlamaMarkets/LendTableFooter.tsx
- packages/curve-ui-kit/.storybook/preview.tsx
- packages/curve-ui-kit/src/utils/searchText.ts
- Make the token search consistent across pages (router, pool creation, pool list pages)
> fix: consistent token search

- apps/main/src/dex/components/ComboBoxSelectToken/types.ts
- packages/curve-ui-kit/src/utils/searchText.ts
- packages/eslint-config-custom/index.js
- forbid packages from importing apps
- fix errors
> chore: forbid packages from importing apps

- apps/main/src/dao/components/PageAnalytics/DailyLocksChart/PositiveAndNegativeBarChart.tsx
- apps/main/src/dao/components/PageAnalytics/DailyLocksChart/PositiveAndNegativeBarChartTooltip.tsx
- apps/main/src/dao/store/createAnalyticsSlice.ts
- apps/main/src/dao/types/dao.types.ts
> refactor: use prices api for dao daily locks

- apps/main/package.json
- yarn.lock
Changes:
- Upgraded curve-js to 2.66.5
> chore: upgrade @curvefi/api to 2.66.5

- apps/main/src/dex/components/PagePool/Page.tsx
- hide the connect wallet prompt when on the pool details page
> feat: show pool page without wallet connected

- packages/external-rewards/src/campaign-list.json
- packages/external-rewards/src/campaigns/Pumpbtc.json
- packages/external-rewards/src/campaigns/index.ts
> External rewards: add PumpBTC campaign

- apps/main/src/dex/components/PagePool/index.tsx
- apps/main/src/dex/components/PoolLabel.tsx
Removed pool type label from the pool page title comp
> refactor: remove pool type label from pool page

- apps/main/src/loan/entities/scrvusdUserBalances.ts
- apps/main/src/loan/entities/scrvusdUserStats.ts
- apps/main/src/loan/entities/scrvusdYield.ts
Changes:
- Temporarily revert scrvusd react-query validation suites
> fix: revert scrvusd query validation suites temporarily

- apps/main/package.json
- apps/main/src/dex/components/PageDashboard/components/SummaryTotal.tsx
- apps/main/src/dex/components/PageDashboard/components/TableRowNoResult.tsx
- apps/main/src/dex/components/PageDashboard/index.tsx
- apps/main/src/dex/lib/curvejs.ts
- apps/main/src/dex/store/createDashboardSlice.ts
- apps/main/src/dex/store/createUserSlice.ts
- yarn.lock
- improve error handling so the dashboard shows errors when the RPC fails
> fix: show errors when dashboard fails loading

- apps/main/src/lend/store/createMarketListSlice.ts
- fixes issue that duplicated all items if you sort (by collateral, for example)
> fix: duplicate results in lend table

- apps/main/src/dex/components/PageCreatePool/constants.ts
From experiments in prod, we observe a need to update offpeg multipliers significantly. This pr does this.
> Update default offpeg fee multipliers

- apps/main/package.json
- apps/main/src/dex/components/PagePoolList/components/PoolRow.tsx
- apps/main/src/dex/components/PagePoolList/components/TableRow.tsx
- apps/main/src/dex/components/PagePoolList/index.tsx
- apps/main/src/dex/lib/curvejs.ts
- apps/main/src/dex/store/createNetworksSlice.ts
- apps/main/src/dex/types/main.types.ts
- yarn.lock
- depends on https://github.com/curvefi/curve-js/pull/448
> feat: enable tokenApy for Sonic

- apps/main/src/dex/components/PagePoolList/Page.tsx
- apps/main/src/dex/components/PagePoolList/components/TableHead.tsx
- apps/main/src/dex/components/PagePoolList/types.ts
- apps/main/src/dex/store/createPoolListSlice.ts
- fixes the sorting in the rewards column for lite networks
> fix: sort by rewards in lite

- apps/main/src/lend/components/DetailsUser/components/DetailsUserLoan.tsx
Changes:
- Hide PNL from lend manage loan view until the algo has been updated
> fix: hide lend pnl data

- packages/curve-ui-kit/package.json
- yarn.lock
Changes:
- Bumped @web3-onboard/trezor to 2.4.7
> chore: bump @web3-onboard/trezor to 2.4.7

- apps/main/src/loan/components/PageLlamaMarkets/cells/PriceCell.tsx
- apps/main/src/loan/entities/llama-market-stats.ts
- apps/main/src/loan/entities/llama-markets.ts
- redirect to the management page if the user has a position
- fixes the lend token
- fixes the token prices when there is no borrow
> fix: market url and lend positions

- apps/main/src/lend/store/createOhlcChartSlice.ts
- apps/main/src/loan/store/createOhlcChartSlice.ts
- packages/prices-api/package.json
- packages/prices-api/src/llamma/models.ts
- packages/prices-api/src/llamma/parsers.ts
- packages/prices-api/src/llamma/responses.ts
> fix:  revert #775

- apps/main/src/loan/layout/Header.tsx
> fix: crash on switch to crvUSD

- apps/main/package.json
- apps/main/src/dex/lib/networks.ts
- yarn.lock
Changes:
- Enabled full support for Sonic on /dex
- Bumped curve-js to 2.66.11 https://github.com/curvefi/curve-js/pull/452
> feat: migrate sonic from lite to full

- apps/main/src/dao/components/PageGauge/GaugeVotesTable/index.tsx
- apps/main/src/dao/components/PageGauges/GaugeListItem/GaugeDetails.tsx
- apps/main/src/dao/components/PageGauges/GaugeListItem/GaugeDetailsSm.tsx
- apps/main/src/dao/components/PageGauges/GaugeVoting/VoteGaugeField/index.tsx
- apps/main/src/dao/components/PageProposal/ProposalInformation/index.tsx
- apps/main/src/dao/components/PageUser/UserGaugeVotesTable/index.tsx
- apps/main/src/dao/components/PageUser/UserLocksTable/index.tsx
- apps/main/src/dao/components/PageUser/UserProposalVotesTable/index.tsx
- apps/main/src/dex/components/PageDashboard/components/FormVecrv.tsx
- apps/main/src/dex/components/PagePool/PoolDetails/ChartOhlcWrapper/LiquidityData.tsx
- apps/main/src/dex/components/PagePool/PoolDetails/ChartOhlcWrapper/TradesData.tsx
- apps/main/src/dex/components/PagePool/PoolDetails/PoolParameters/index.tsx
- apps/main/src/lend/components/ChartOhlcWrapper/LiquidityData.tsx
- apps/main/src/lend/components/ChartOhlcWrapper/TradesData.tsx
- apps/main/src/loan/components/ChartOhlcWrapper/LiquidityData.tsx
- apps/main/src/loan/components/ChartOhlcWrapper/TradesData.tsx
- packages/ui/src/CampaignRewards/TooltipMessage.tsx
- packages/ui/src/utils/utilsDate.ts
- packages/ui/src/utils/utilsFormat.ts
Avoid numeric month as that may be interpreted in different ways depending on the browser's locale
> chore: change date format

- apps/main/src/dao/lib/curvejs.ts
- apps/main/src/dex/lib/curvejs.ts
- apps/main/src/lend/lib/apiLending.ts
- apps/main/src/loan/lib/apiCrvusd.ts
- packages/curve-ui-kit/src/lib/ethers.ts
- Sometimes the transaction might revert (e.g. due to slippage) and the user won't receive any feedback
- This PR checks whether the transaction reverted and raises an error if that's the case
> fix: check whether transactions revert

- apps/main/src/loan/components/PageCrvUsdStaking/UserInformation/index.tsx
Changes:
- Updated cowswap link to link to pair: WETH <> scrvUSD
> chore: updated cowswap crvusd staking link

- apps/main/next.config.js
- fixes the integration link in the footer of the DAO app
> fix: DAO integrations link

- apps/main/src/dao/components/PageProposal/ProposalInformation/index.tsx
Changes:
- Ensure proposal data exists before calculating start and end times for proposals
> fix: ensure proposal data exists before calculating start and end times

- apps/main/src/dex/components/PageCreatePool/PoolType/index.tsx
Changes:
- Updated cryptoswap pool type description in pool creation
> fix: update description for cryptoswap pool type

- apps/main/src/lend/store/createOhlcChartSlice.ts
Changes:
- Ensure ohlc endpoint disabled flag is false after a successful API request
> fix: correctly apply ohlc endpoint disabled flag

- apps/main/src/dex/constants.ts
- apps/main/src/dex/store/createCacheSlice.ts
- apps/main/src/lend/networks.ts
- apps/main/src/loan/components/PageLlamaMarkets/Page.tsx
- apps/main/src/loan/components/PageLlamaMarkets/cells/RateCell.tsx
- apps/main/src/loan/components/PageLlamaMarkets/cells/RateCellTooltip.tsx
- apps/main/src/loan/components/PageLlamaMarkets/columns.tsx
- apps/main/src/loan/components/PageLlamaMarkets/filters/MultiSelectFilter.tsx
- apps/main/src/loan/components/PageLlamaMarkets/filters/RangeSliderFilter.tsx
- apps/main/src/loan/entities/campaigns.ts
- packages/curve-ui-kit/src/features/user-profile/store.ts
- packages/curve-ui-kit/src/themes/components/button/mui-button.ts
- tests/cypress/e2e/loan/llamalend-markets.cy.ts
- tests/cypress/tsconfig.json
- tests/tsconfig.json
- update the clear button to follow the design
- update the extra small buttons to use lower case characters (it's only used here and in the [banner](https://github.com/curvefi/curve-frontend/blob/b1f8309938a0579675bf159833e564770b34b7bb/packages/curve-ui-kit/src/shared/ui/Banner.tsx#L80))
- hide lend chart by default since it's similar to the borrow one
- removes duplicate rewards displayed in lend and borrow columns
- fixes scaling issue on the rewards points logo
- review comments from #845
> feat: llamalend table adjustments

- packages/external-rewards/src/campaign-list.json
- packages/external-rewards/src/campaigns/Ethena.json
- packages/external-rewards/src/campaigns/Zunami.json
- packages/external-rewards/src/campaigns/index.ts
- Fix description text on Ethena campaign
- Add Zunami campaign
> External rewards: update campaigns

- packages/external-rewards/src/campaigns/Fx.json
- Add new pool on FXN campaign
> External rewards: update campaign

- apps/main/src/loan/components/LoanInfoUser/components/UserInfos.tsx
- Change the breakpoint to a custom size so it wraps up properly
- The layout is currently broken for screens between 426px and 840px
> fix: update breakpoint

- apps/main/src/dao/components/PageGauges/GaugeListItem/index.tsx
- apps/main/src/dao/components/PageGauges/GaugeVoting/VoteGaugeField/index.tsx
- apps/main/src/dao/entities/user-gauge-vote-next-time.ts
- apps/main/src/dao/entities/user-gauge-weight-votes.ts
- apps/main/src/dao/entities/validation/curvejs-validation.ts
- apps/main/src/dao/store/createGaugesSlice.ts
- packages/curve-ui-kit/src/lib/model/query/root-keys.ts
- packages/curve-ui-kit/src/lib/model/query/user-validation.ts
- fixes conflicts that were not detected properly in #884 due to new  code introduced in #851
> fix: dao new queries with connection context

- apps/main/src/dao/hooks/useProposalsList.ts
Changes:
- Fixed 'ending soon' sorting option to behave as expected
> refactor: fix ending soon sorting order

- packages/external-rewards/src/campaigns/Symbiotic.json
> External rewards: update Symbiotic campaign

- apps/main/src/loan/components/PageMarketList/Page.tsx
- apps/main/src/loan/components/PageMarketList/components/TableHead/TableHead.tsx
- apps/main/src/loan/components/PageMarketList/components/TableRow/TableRowNoResult.tsx
- apps/main/src/loan/components/PageMarketList/components/TableSettings/TableSettings.tsx
- apps/main/src/loan/components/PageMarketList/index.tsx
- apps/main/src/loan/components/PageMarketList/types.ts
- apps/main/src/loan/store/createCollateralListSlice.ts
- Move the filters from store to state.
- The filters were not refreshed until reload because they were not included in the useEffect.
- similar to https://github.com/curvefi/curve-frontend/pull/901
> fix: crvUSD filters

- apps/main/src/loan/components/PagePegKeepers/components/PegKeeperForm.tsx
- apps/main/src/loan/store/createPegKeepersSlice.ts
Changes:
- Handle contract read errors more gracefully while allowing all read calls to get the chance to complete and display data in pegkeeper contract reads
> refactor: improve PegKeeperForm and createPegKeepersSlice error handling

- apps/main/src/dex/lib/networks.ts
- packages/curve-ui-kit/src/utils/network.ts
- packages/ui/src/utils/utilsNetworks.ts
- change link from /token to /address, only for Hyperliquid
> fix: hyperliquid explore token links

- .github/workflows/ci.yaml
- apps/main/src/app/crvusd/[network]/markets/[collateralId]/collateral.utils.ts
- apps/main/src/app/crvusd/client.tsx
- apps/main/src/app/lend/[network]/markets/[market]/market-name.utils.ts
- apps/main/src/lend/components/PageLoanCreate/Page.tsx
- apps/main/src/lend/components/PageLoanManage/Page.tsx
- apps/main/src/lend/components/PageVault/Page.tsx
- apps/main/src/lend/entities/chain/chain-hooks.ts
- apps/main/src/lend/utils/utilsRouter.ts
- apps/main/src/loan/components/PageLoanCreate/Page.tsx
- apps/main/src/loan/components/PageLoanManage/Page.tsx
- apps/main/src/loan/entities/llama-markets.ts
- apps/main/src/loan/utils/utilsRouter.ts
- packages/curve-ui-kit/src/features/connect-wallet/lib/ConnectionContext.tsx
- packages/curve-ui-kit/src/features/connect-wallet/lib/useWallet.ts
- tests/cypress/e2e/lend/basic.cy.ts
- Support both upper and lower case in URL.
- Redirect to the market list when not found.
- Refactor URL parsing
- Fix cross-app conflicts when creating the curveJS libraries
> fix: lend/loan casing in url

- .github/dependabot.yml
- even though the file parses fine in many validators, dependabot cannot read the * in the string
> fix: dependabot yml

- apps/main/src/dao/components/ProposalVoteStatusBox/index.tsx
Changes:
- Correctly format current support in proposal votes
> fix: correctly format current support for proposal

- packages/external-rewards/src/campaigns/Ethena.json
- Add new pools on hyperliquid
> External rewards: update Ethena campaign 

- apps/main/src/dex/components/PageDeployGauge/InfoBox.tsx
Changes:
- Updated gauge deployment info box text
> chore: update gauge deployment info text

- packages/curve-ui-kit/src/utils/index.ts
- whitelist both www.curve.finance and https://curve.finance
> fix: turn off beta by default

- apps/main/package.json
- apps/main/src/app/api/lend/route.ts
- apps/main/src/dao/store/createGaugesSlice.ts
- apps/main/src/dex/lib/curvejs.ts
- apps/main/src/dex/store/createGlobalSlice.ts
- apps/main/src/loan/entities/appstats-daily-volume.ts
- packages/ui/src/utils/utilsNetworks.ts
- tests/cypress/e2e/lend/0-mainnet/0-crv/ethereum-crv-crvusd-loan.cy.ts
- yarn.lock
- update to https://github.com/curvefi/curve-js/pull/469 and https://github.com/curvefi/curve-llamalend.js/pull/21
> chore: revert cloudfront URLs

- packages/ui/src/utils/utilsFormat.ts
* Updated the `formatDate` function to accept both `Date` and `string` types
> fix: date conversion

- packages/external-rewards/src/campaigns/Resolv.json
> External rewards: update Resolv campaign

- packages/external-rewards/src/campaigns/Ethena.json
> External rewards: update Ethena campaign

- packages/curve-ui-kit/src/shared/ui/ActionInfo.tsx
> styling: action info padding

- packages/curve-ui-kit/src/shared/HashRouterRedirect.tsx
- recovers the https://curve.finance/#/integrations/ link
> fix: broken integrations page link

- apps/main/package.json
- packages/tsconfig/ui.json
- packages/ui/src/Chart/CandleChart.tsx
- yarn.lock
This PR just updates the library to the latest version and ensures everything is working ok. A future PR will do further refactoring to take advantage of new features.
Changes:
- Upgraded lightweight-charts to v5 and fix breaking changes
> chore: update lightweight-charts to v5

- packages/curve-ui-kit/src/shared/ui/ButtonMenu.tsx
- packages/curve-ui-kit/src/shared/ui/stories/ButtonMenu.stories.tsx
Button disabled state is not something we've implemented yet, must do that in another PR
> feat: add button menu component

- packages/external-rewards/src/campaign-list.json
- packages/external-rewards/src/campaigns/Asymmetry.json
- packages/external-rewards/src/campaigns/index.ts
- Add Asymmetry campaign (Gem Rush), with campaign start time at 1748433600
> External rewards: Add new campaign

- packages/external-rewards/src/campaign-list.json
- packages/external-rewards/src/campaigns/Asymmetry.json
- packages/external-rewards/src/campaigns/Kalypso.json
- packages/external-rewards/src/campaigns/Radius.json
- packages/external-rewards/src/campaigns/index.ts
- Add Kalypso and Radius campaigns
- Add new pool on Asymetry campaign
> External rewards: add new campaigns and update Asymmetry campaign

- apps/main/src/dex/components/PagePool/PoolDetails/PoolStats/index.tsx
- apps/main/src/dex/lib/curvejs.ts
- apps/main/src/dex/store/createPoolDepositSlice.ts
- apps/main/src/dex/store/createPoolsSlice.ts
- load the pool balances when the wallet is connected
- properly return errors when the wallet is not connected
- remove eslint warning omission
> fix: pool balances

- packages/curve-ui-kit/src/themes/design/2_theme.ts
- packages/curve-ui-kit/src/themes/stories/Button.stories.ts
Copied new colors from Figma style guide colors table
> fix: add disabled states to buttons

- apps/main/src/lend/components/DetailInfoHealth.tsx
- apps/main/src/lend/components/SharedCellData/CellLoanUserHealth.tsx
- apps/main/src/loan/components/DetailInfoHealth.tsx
Changes:
- Always use healthFull for health in mint markets
> fix: always use health full in mint markets

- apps/main/src/loan/components/PageLlamaMarkets/LlamaMarketsTable.tsx
- apps/main/src/loan/components/PageLlamaMarkets/Page.tsx
- simple rename in a separate PR for easy review
> refactor: rename table component

- packages/external-rewards/src/campaigns/Asymmetry.json
> External rewards: update Asymmetry campaign

- packages/external-rewards/src/campaigns/Sonic.json
https://docs.soniclabs.com/funding/sonic-airdrop/sonic-points#whitelisted-assets
> External rewards: update Sonic multipliers

- apps/main/src/loan/components/PageLlamaMarkets/LlamaMarketExpandedPanel.tsx
- packages/curve-ui-kit/src/shared/ui/Metric.tsx
- packages/curve-ui-kit/src/shared/ui/stories/Metric.stories.tsx
Changes:
- Adds support for setting a custom font color for value in Metric component
> feat: add support for custom value font color in Metric

- apps/main/src/app/GlobalLayout.tsx
- extend the page to the available space
> fix: page width

- apps/main/src/llamalend/entities/llama-markets.ts
- also update the address of the token so the correct icon is displayed
> fix: show ETH icon for WETH mint markets

- apps/main/package.json
- yarn.lock
- https://github.com/curvefi/curve-js/pull/486
> feat: hidden pools for lite networks

- packages/external-rewards/src/campaigns/Resolv.json
> External rewards: update Resolv campaign 

- apps/main/src/app/GlobalLayout.tsx
- apps/main/src/dex/components/ChipPool.tsx
- apps/main/src/globalStyle.ts
- apps/main/src/llamalend/entities/crvusd-snapshots.ts
- apps/main/src/llamalend/entities/lending-snapshots.ts
- packages/curve-ui-kit/src/widgets/Disclaimer/Disclaimer.tsx
- tests/cypress/e2e/all/disclaimers.cy.ts
- tests/cypress/e2e/all/header.cy.ts
- tests/cypress/e2e/llamalend/llamalend-markets.cy.ts
- tests/cypress/support/helpers/minting-mocks.ts
- tests/cypress/support/ui.ts
- expand header to 100vw when mobile drawer is open
- adjust dex table to not expand too much
- pass fetch_on_chain to snapshot endpoints
> fix: page width issues, e2e errors

- packages/curve-ui-kit/package.json
- packages/curve-ui-kit/src/features/connect-wallet/lib/wagmi/connectors.ts
- packages/curve-ui-kit/src/features/connect-wallet/lib/wagmi/wallets.ts
- packages/curve-ui-kit/src/shared/icons/BinanceWalletIcon.tsx
- yarn.lock
Basically a duplicate of "Browser Wallet"
> feat: add binance wallet option

- packages/external-rewards/src/campaigns/TacTokens.json
> External rewards: update TAC tokens campaign

- packages/curve-ui-kit/src/features/market-details/index.tsx
Changes:
- Fixed the utilization calculation in the new Market Details
> fix: market details utilization calculation

- packages/curve-ui-kit/src/shared/routes.ts
- packages/curve-ui-kit/src/widgets/Header/Header.tsx
- packages/curve-ui-kit/src/widgets/Header/types.ts
> feat: remove crvusd and lend pages from nav, but keep routing intact

- apps/main/package.json
- yarn.lock
Changes:
- Reverted back to llamalend-js 1.0.24
> fix: revert back to llamalend-js 1.0.24

- apps/main/package.json
- yarn.lock
Changes:
- Bumped llamalend-js to 1.0.27
> chore: bumped llamalend-js to 1.0.27

- packages/prices-api/package.json
- packages/prices-api/src/pools/api.ts
There was another use of broken pagination
> fix: remove prices api pagination

- apps/main/index.html
- apps/main/src/dex/components/PageRouterSwap/Page.tsx
- apps/main/src/main.tsx
- apps/main/src/routes/GlobalLayout.tsx
- apps/main/src/routes/index.tsx
- apps/main/src/routes/root.routes.tsx
- packages/curve-ui-kit/src/pages/ErrorPage.tsx
- packages/curve-ui-kit/src/widgets/ErrorBoundary.tsx
- packages/ui/src/utils/utilsConstants.ts
- tests/cypress/e2e/main/basic.cy.ts
- update the 404 to receive title and subtitle
- show the error page when errors occur
- add a few error boundaries for errors in different levels
- add a couple tests
> feat: error page and boundary

- apps/main/src/llamalend/entities/llama-markets.ts
- packages/prices-api/src/crvusd/api.ts
- packages/prices-api/src/crvusd/models.ts
- packages/prices-api/src/crvusd/parsers.ts
- packages/prices-api/src/crvusd/responses.ts
the order was inverted in the backend recently and broke the links to the sfrxETH markets
> fix: mint market links

- apps/main/src/llamalend/LlamaMarketsPage/header-tooltips/BorrowRateHeaderTooltipContent.tsx
Changes:
- Updated llamalend markets list borrow rate column header tooltip
> fix: update llamalend markets borrow rate column header tooltip

- apps/main/src/dex/components/PageRouterSwap/components/DetailInfoTradeRouteRoute.tsx
- apps/main/src/dex/lib/networks.ts
- apps/main/src/dex/store/createIntegrationsSlice.ts
- apps/main/src/dex/store/createNetworksSlice.ts
- apps/main/src/lend/hooks/useBorrowPositionDetails.ts
- apps/main/src/lend/hooks/useMarketDetails.tsx
- apps/main/src/lend/hooks/useSupplyPositionDetails.ts
- apps/main/src/lend/networks.ts
- apps/main/src/llamalend/entities/mint-markets.ts
- apps/main/src/loan/hooks/useLoanPositionDetails.ts
- apps/main/src/loan/hooks/useMarketDetails.ts
- apps/main/src/loan/networks.ts
- apps/main/src/loan/store/createCollateralsSlice.ts
- packages/curve-ui-kit/src/entities/crvusd-snapshots.ts
- packages/curve-ui-kit/src/lib/model/query/root-keys.ts
- improve type safety and consistency in how network and chain identifiers are handled. 
- removes unnecessary type assertions
- simplifies logic for mapping and accessing network data
> refactor: simplify network types

- apps/main/src/dao/components/PageGauge/GaugeMetrics/index.tsx
- apps/main/src/dao/components/PageGauge/GaugeVotesTable/index.tsx
- apps/main/src/dao/components/PageUser/UserGaugeVotesTable/index.tsx
- apps/main/src/dao/components/PageUser/UserLocksTable/index.tsx
- apps/main/src/dao/components/PageUser/UserProposalVotesTable/index.tsx
- apps/main/src/dex/components/PageDashboard/components/FormVecrv.tsx
- packages/ui/src/utils/utilsDate.ts
- simplifies some date calculations that were repeated and unnecessary
- depends on #1322
> refactor: simplify date formatting

- apps/main/src/lend/components/PageLoanCreate/index.tsx
- apps/main/src/lend/components/PageLoanManage/index.tsx
- packages/ui/src/AppForm/styles.ts
Fixes weird tab spacing, only happened on lend, not loan.
> fix: lend tab spacing

- apps/main/src/llamalend/widgets/borrow/components/BorrowActionInfoAccordion.tsx
- apps/main/src/llamalend/widgets/borrow/components/BorrowTabContents.tsx
- packages/curve-ui-kit/src/features/slippage-settings/ui/SlippageSettings.tsx
- add a settings icon to customize the slippage
- depends on #1315
> feat: borrow form slippage tolerance settings

- apps/main/public/robots.txt
- create a new robots file with the simplest instructions
- following guidelines by WEDF
> chore: create robots file

- packages/external-rewards/src/campaigns/YieldFi.json
> External rewards: update YieldFi campaign

- packages/external-rewards/src/campaigns/Elixir.json
> External rewards: update Elixir campaign

- packages/curve-ui-kit/src/widgets/Header/Header.tsx
Changes:
- Removes phishing warning modal
> feat: remove phishing warning modal
